// Generated by the vmap overload generator (see docs/design/vmap.md, "API"). One overload per
// pair of per-example input and output kinds; the batched types prepend Named<N, A>.
@file:OptIn(kotlin.experimental.ExperimentalTypeInference::class)

package io.tlaloc.autograd

import io.tlaloc.core.DTensor
import io.tlaloc.core.DType
import io.tlaloc.core.ExperimentalTlalocApi
import io.tlaloc.core.F32
import io.tlaloc.core.F64
import io.tlaloc.core.IndexName
import io.tlaloc.core.Named
import io.tlaloc.core.Rank1
import io.tlaloc.core.Rank2
import io.tlaloc.core.Rank3
import io.tlaloc.core.Rank4
import io.tlaloc.core.ScalarShape
import io.tlaloc.core.Shape
import io.tlaloc.core.ShapeAtom
import kotlin.jvm.JvmName

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T0_T0")
fun <N : IndexName, A : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<ScalarShape, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T0_T1")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<ScalarShape, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T0_T2")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<ScalarShape, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T0_T3")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<ScalarShape, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T0_F")
fun <N : IndexName, A : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<ScalarShape, F32>) -> Float,
): (DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T0_Dd")
fun <N : IndexName, A : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<ScalarShape, F64>) -> Double,
): (DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T0_E")
fun <N : IndexName, A : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<ScalarShape, D>) -> DTensor<Shape, D>,
): (DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Shape, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T1_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank1<S0>, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T1_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank1<S0>, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T1_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank1<S0>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T1_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank1<S0>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T1_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank1<S0>, F32>) -> Float,
): (DTensor<Rank2<Named<N, A>, S0>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T1_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank1<S0>, F64>) -> Double,
): (DTensor<Rank2<Named<N, A>, S0>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T1_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank1<S0>, D>) -> DTensor<Shape, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>) -> DTensor<Shape, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T2_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank2<S0, S1>, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T2_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank2<S0, S1>, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T2_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank2<S0, S1>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T2_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank2<S0, S1>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T2_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank2<S0, S1>, F32>) -> Float,
): (DTensor<Rank3<Named<N, A>, S0, S1>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T2_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank2<S0, S1>, F64>) -> Double,
): (DTensor<Rank3<Named<N, A>, S0, S1>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T2_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank2<S0, S1>, D>) -> DTensor<Shape, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>) -> DTensor<Shape, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T3_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank3<S0, S1, S2>, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T3_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank3<S0, S1, S2>, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T3_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank3<S0, S1, S2>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T3_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank3<S0, S1, S2>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T3_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank3<S0, S1, S2>, F32>) -> Float,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T3_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank3<S0, S1, S2>, F64>) -> Double,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_T3_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, D : DType> vmap(
    axis: BatchAxis<N, A>,
    f: (DTensor<Rank3<S0, S1, S2>, D>) -> DTensor<Shape, D>,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, D>) -> DTensor<Shape, D> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_F_T0")
fun <N : IndexName, A : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Float) -> DTensor<ScalarShape, F32>,
): (DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_F_T1")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Float) -> DTensor<Rank1<T0>, F32>,
): (DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Rank2<Named<N, A>, T0>, F32> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_F_T2")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Float) -> DTensor<Rank2<T0, T1>, F32>,
): (DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Rank3<Named<N, A>, T0, T1>, F32> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_F_T3")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Float) -> DTensor<Rank3<T0, T1, T2>, F32>,
): (DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, F32> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_F_F")
fun <N : IndexName, A : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Float) -> Float,
): (DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_F_E")
fun <N : IndexName, A : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Float) -> DTensor<Shape, F32>,
): (DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Shape, F32> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_Dd_T0")
fun <N : IndexName, A : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Double) -> DTensor<ScalarShape, F64>,
): (DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_Dd_T1")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Double) -> DTensor<Rank1<T0>, F64>,
): (DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Rank2<Named<N, A>, T0>, F64> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_Dd_T2")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Double) -> DTensor<Rank2<T0, T1>, F64>,
): (DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Rank3<Named<N, A>, T0, T1>, F64> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_Dd_T3")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Double) -> DTensor<Rank3<T0, T1, T2>, F64>,
): (DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, F64> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_Dd_Dd")
fun <N : IndexName, A : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Double) -> Double,
): (DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap_Dd_E")
fun <N : IndexName, A : ShapeAtom> vmap(
    axis: BatchAxis<N, A>,
    f: (Double) -> DTensor<Shape, F64>,
): (DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Shape, F64> = { _ -> pluginMissing("vmap") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T0_T0")
fun <N : IndexName, A : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<ScalarShape, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T0_T1")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<ScalarShape, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T0_T2")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<ScalarShape, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T0_T3")
fun <N : IndexName, A : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<ScalarShape, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T0_F")
fun <N : IndexName, A : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, F32>, DTensor<ScalarShape, F32>) -> Float,
): (DTensor<Rank1<Named<N, A>>, F32>, DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T0_Dd")
fun <N : IndexName, A : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, F64>, DTensor<ScalarShape, F64>) -> Double,
): (DTensor<Rank1<Named<N, A>>, F64>, DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T0_E")
fun <N : IndexName, A : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<ScalarShape, D>) -> DTensor<Shape, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T1_T0")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<Rank1<U0>, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T1_T1")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<Rank1<U0>, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T1_T2")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<Rank1<U0>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T1_T3")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<Rank1<U0>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T1_F")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, F32>, DTensor<Rank1<U0>, F32>) -> Float,
): (DTensor<Rank1<Named<N, A>>, F32>, DTensor<Rank2<Named<N, A>, U0>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T1_Dd")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, F64>, DTensor<Rank1<U0>, F64>) -> Double,
): (DTensor<Rank1<Named<N, A>>, F64>, DTensor<Rank2<Named<N, A>, U0>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T1_E")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<Rank1<U0>, D>) -> DTensor<Shape, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T2_T0")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T2_T1")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T2_T2")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T2_T3")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T2_F")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, F32>, DTensor<Rank2<U0, U1>, F32>) -> Float,
): (DTensor<Rank1<Named<N, A>>, F32>, DTensor<Rank3<Named<N, A>, U0, U1>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T2_Dd")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, F64>, DTensor<Rank2<U0, U1>, F64>) -> Double,
): (DTensor<Rank1<Named<N, A>>, F64>, DTensor<Rank3<Named<N, A>, U0, U1>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_T2_E")
fun <N : IndexName, A : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<ScalarShape, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Shape, D>,
): (DTensor<Rank1<Named<N, A>>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T0_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<ScalarShape, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T0_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<ScalarShape, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T0_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<ScalarShape, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T0_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<ScalarShape, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T0_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, F32>, DTensor<ScalarShape, F32>) -> Float,
): (DTensor<Rank2<Named<N, A>, S0>, F32>, DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T0_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, F64>, DTensor<ScalarShape, F64>) -> Double,
): (DTensor<Rank2<Named<N, A>, S0>, F64>, DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T0_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<ScalarShape, D>) -> DTensor<Shape, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T1_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<Rank1<U0>, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T1_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<Rank1<U0>, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T1_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<Rank1<U0>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T1_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<Rank1<U0>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T1_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, F32>, DTensor<Rank1<U0>, F32>) -> Float,
): (DTensor<Rank2<Named<N, A>, S0>, F32>, DTensor<Rank2<Named<N, A>, U0>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T1_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, F64>, DTensor<Rank1<U0>, F64>) -> Double,
): (DTensor<Rank2<Named<N, A>, S0>, F64>, DTensor<Rank2<Named<N, A>, U0>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T1_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<Rank1<U0>, D>) -> DTensor<Shape, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T2_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T2_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T2_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T2_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T2_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, F32>, DTensor<Rank2<U0, U1>, F32>) -> Float,
): (DTensor<Rank2<Named<N, A>, S0>, F32>, DTensor<Rank3<Named<N, A>, U0, U1>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T2_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, F64>, DTensor<Rank2<U0, U1>, F64>) -> Double,
): (DTensor<Rank2<Named<N, A>, S0>, F64>, DTensor<Rank3<Named<N, A>, U0, U1>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_T2_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank1<S0>, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Shape, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T0_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<ScalarShape, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T0_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<ScalarShape, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T0_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<ScalarShape, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T0_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<ScalarShape, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T0_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, F32>, DTensor<ScalarShape, F32>) -> Float,
): (DTensor<Rank3<Named<N, A>, S0, S1>, F32>, DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T0_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, F64>, DTensor<ScalarShape, F64>) -> Double,
): (DTensor<Rank3<Named<N, A>, S0, S1>, F64>, DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T0_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<ScalarShape, D>) -> DTensor<Shape, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T1_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<Rank1<U0>, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T1_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<Rank1<U0>, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T1_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<Rank1<U0>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T1_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<Rank1<U0>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T1_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, F32>, DTensor<Rank1<U0>, F32>) -> Float,
): (DTensor<Rank3<Named<N, A>, S0, S1>, F32>, DTensor<Rank2<Named<N, A>, U0>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T1_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, F64>, DTensor<Rank1<U0>, F64>) -> Double,
): (DTensor<Rank3<Named<N, A>, S0, S1>, F64>, DTensor<Rank2<Named<N, A>, U0>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T1_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<Rank1<U0>, D>) -> DTensor<Shape, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T2_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<ScalarShape, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T2_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T2_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T2_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T2_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, F32>, DTensor<Rank2<U0, U1>, F32>) -> Float,
): (DTensor<Rank3<Named<N, A>, S0, S1>, F32>, DTensor<Rank3<Named<N, A>, U0, U1>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T2_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, F64>, DTensor<Rank2<U0, U1>, F64>) -> Double,
): (DTensor<Rank3<Named<N, A>, S0, S1>, F64>, DTensor<Rank3<Named<N, A>, U0, U1>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_T2_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, U0 : ShapeAtom, U1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Batched,
    f: (DTensor<Rank2<S0, S1>, D>, DTensor<Rank2<U0, U1>, D>) -> DTensor<Shape, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_X_T0")
fun <N : IndexName, A : ShapeAtom, V, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<ScalarShape, D>, V) -> DTensor<ScalarShape, D>,
): (DTensor<Rank1<Named<N, A>>, D>, V) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_X_T1")
fun <N : IndexName, A : ShapeAtom, V, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<ScalarShape, D>, V) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, V) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_X_T2")
fun <N : IndexName, A : ShapeAtom, V, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<ScalarShape, D>, V) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, V) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_X_T3")
fun <N : IndexName, A : ShapeAtom, V, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<ScalarShape, D>, V) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank1<Named<N, A>>, D>, V) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_X_F")
fun <N : IndexName, A : ShapeAtom, V> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<ScalarShape, F32>, V) -> Float,
): (DTensor<Rank1<Named<N, A>>, F32>, V) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_X_Dd")
fun <N : IndexName, A : ShapeAtom, V> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<ScalarShape, F64>, V) -> Double,
): (DTensor<Rank1<Named<N, A>>, F64>, V) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T0_X_E")
fun <N : IndexName, A : ShapeAtom, V, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<ScalarShape, D>, V) -> DTensor<Shape, D>,
): (DTensor<Rank1<Named<N, A>>, D>, V) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T0_T0")
fun <N : IndexName, A : ShapeAtom, W, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<ScalarShape, D>) -> DTensor<ScalarShape, D>,
): (W, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T0_T1")
fun <N : IndexName, A : ShapeAtom, W, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<ScalarShape, D>) -> DTensor<Rank1<T0>, D>,
): (W, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T0_T2")
fun <N : IndexName, A : ShapeAtom, W, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<ScalarShape, D>) -> DTensor<Rank2<T0, T1>, D>,
): (W, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T0_T3")
fun <N : IndexName, A : ShapeAtom, W, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<ScalarShape, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (W, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T0_F")
fun <N : IndexName, A : ShapeAtom, W> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<ScalarShape, F32>) -> Float,
): (W, DTensor<Rank1<Named<N, A>>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T0_Dd")
fun <N : IndexName, A : ShapeAtom, W> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<ScalarShape, F64>) -> Double,
): (W, DTensor<Rank1<Named<N, A>>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T0_E")
fun <N : IndexName, A : ShapeAtom, W, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<ScalarShape, D>) -> DTensor<Shape, D>,
): (W, DTensor<Rank1<Named<N, A>>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_X_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, V, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank1<S0>, D>, V) -> DTensor<ScalarShape, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, V) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_X_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, V, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank1<S0>, D>, V) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, V) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_X_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, V, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank1<S0>, D>, V) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, V) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_X_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, V, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank1<S0>, D>, V) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, V) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_X_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, V> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank1<S0>, F32>, V) -> Float,
): (DTensor<Rank2<Named<N, A>, S0>, F32>, V) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_X_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, V> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank1<S0>, F64>, V) -> Double,
): (DTensor<Rank2<Named<N, A>, S0>, F64>, V) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T1_X_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, V, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank1<S0>, D>, V) -> DTensor<Shape, D>,
): (DTensor<Rank2<Named<N, A>, S0>, D>, V) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T1_T0")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank1<U0>, D>) -> DTensor<ScalarShape, D>,
): (W, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T1_T1")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank1<U0>, D>) -> DTensor<Rank1<T0>, D>,
): (W, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T1_T2")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank1<U0>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (W, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T1_T3")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank1<U0>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (W, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T1_F")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank1<U0>, F32>) -> Float,
): (W, DTensor<Rank2<Named<N, A>, U0>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T1_Dd")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank1<U0>, F64>) -> Double,
): (W, DTensor<Rank2<Named<N, A>, U0>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T1_E")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank1<U0>, D>) -> DTensor<Shape, D>,
): (W, DTensor<Rank2<Named<N, A>, U0>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_X_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, V, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank2<S0, S1>, D>, V) -> DTensor<ScalarShape, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, V) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_X_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, V, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank2<S0, S1>, D>, V) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, V) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_X_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, V, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank2<S0, S1>, D>, V) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, V) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_X_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, V, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank2<S0, S1>, D>, V) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, V) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_X_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, V> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank2<S0, S1>, F32>, V) -> Float,
): (DTensor<Rank3<Named<N, A>, S0, S1>, F32>, V) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_X_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, V> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank2<S0, S1>, F64>, V) -> Double,
): (DTensor<Rank3<Named<N, A>, S0, S1>, F64>, V) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T2_X_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, V, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank2<S0, S1>, D>, V) -> DTensor<Shape, D>,
): (DTensor<Rank3<Named<N, A>, S0, S1>, D>, V) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T2_T0")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank2<U0, U1>, D>) -> DTensor<ScalarShape, D>,
): (W, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T2_T1")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank1<T0>, D>,
): (W, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T2_T2")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (W, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T2_T3")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank2<U0, U1>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (W, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T2_F")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank2<U0, U1>, F32>) -> Float,
): (W, DTensor<Rank3<Named<N, A>, U0, U1>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T2_Dd")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank2<U0, U1>, F64>) -> Double,
): (W, DTensor<Rank3<Named<N, A>, U0, U1>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T2_E")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank2<U0, U1>, D>) -> DTensor<Shape, D>,
): (W, DTensor<Rank3<Named<N, A>, U0, U1>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T3_X_T0")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, V, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank3<S0, S1, S2>, D>, V) -> DTensor<ScalarShape, D>,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, D>, V) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T3_X_T1")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, V, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank3<S0, S1, S2>, D>, V) -> DTensor<Rank1<T0>, D>,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, D>, V) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T3_X_T2")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, V, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank3<S0, S1, S2>, D>, V) -> DTensor<Rank2<T0, T1>, D>,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, D>, V) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T3_X_T3")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, V, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank3<S0, S1, S2>, D>, V) -> DTensor<Rank3<T0, T1, T2>, D>,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, D>, V) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T3_X_F")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, V> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank3<S0, S1, S2>, F32>, V) -> Float,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, F32>, V) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T3_X_Dd")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, V> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank3<S0, S1, S2>, F64>, V) -> Double,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, F64>, V) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_T3_X_E")
fun <N : IndexName, A : ShapeAtom, S0 : ShapeAtom, S1 : ShapeAtom, S2 : ShapeAtom, V, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Batched,
    second: Broadcast,
    f: (DTensor<Rank3<S0, S1, S2>, D>, V) -> DTensor<Shape, D>,
): (DTensor<Rank4<Named<N, A>, S0, S1, S2>, D>, V) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T3_T0")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, U2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank3<U0, U1, U2>, D>) -> DTensor<ScalarShape, D>,
): (W, DTensor<Rank4<Named<N, A>, U0, U1, U2>, D>) -> DTensor<Rank1<Named<N, A>>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T3_T1")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, U2 : ShapeAtom, T0 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank3<U0, U1, U2>, D>) -> DTensor<Rank1<T0>, D>,
): (W, DTensor<Rank4<Named<N, A>, U0, U1, U2>, D>) -> DTensor<Rank2<Named<N, A>, T0>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T3_T2")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, U2 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank3<U0, U1, U2>, D>) -> DTensor<Rank2<T0, T1>, D>,
): (W, DTensor<Rank4<Named<N, A>, U0, U1, U2>, D>) -> DTensor<Rank3<Named<N, A>, T0, T1>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T3_T3")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, U2 : ShapeAtom, T0 : ShapeAtom, T1 : ShapeAtom, T2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank3<U0, U1, U2>, D>) -> DTensor<Rank3<T0, T1, T2>, D>,
): (W, DTensor<Rank4<Named<N, A>, U0, U1, U2>, D>) -> DTensor<Rank4<Named<N, A>, T0, T1, T2>, D> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T3_F")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, U2 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank3<U0, U1, U2>, F32>) -> Float,
): (W, DTensor<Rank4<Named<N, A>, U0, U1, U2>, F32>) -> DTensor<Rank1<Named<N, A>>, F32> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T3_Dd")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, U2 : ShapeAtom> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank3<U0, U1, U2>, F64>) -> Double,
): (W, DTensor<Rank4<Named<N, A>, U0, U1, U2>, F64>) -> DTensor<Rank1<Named<N, A>>, F64> = { _, _ -> pluginMissing("vmap2") }

@ExperimentalTlalocApi
@OverloadResolutionByLambdaReturnType
@JvmName("vmap2_X_T3_E")
fun <N : IndexName, A : ShapeAtom, W, U0 : ShapeAtom, U1 : ShapeAtom, U2 : ShapeAtom, D : DType> vmap2(
    axis: BatchAxis<N, A>,
    first: Broadcast,
    second: Batched,
    f: (W, DTensor<Rank3<U0, U1, U2>, D>) -> DTensor<Shape, D>,
): (W, DTensor<Rank4<Named<N, A>, U0, U1, U2>, D>) -> DTensor<Shape, D> = { _, _ -> pluginMissing("vmap2") }
