/**
 * §0.4.449 — the DxirFunction → Kotlin source pretty-printer: the north star's
 * flagship surface (Tlaloc as an improved Tangent / DiffKT — the reverse code
 * must be READABLE by the user as Kotlin source, AND COMPILED). Where Tangent
 * prints Python it cannot type, this prints a complete, compilable Kotlin
 * function over the `:core` DTensor host twins: every body op becomes a `val`
 * bound to the certified host-twin call spelling (`matmul`, `sumToLike`,
 * `embeddingGrad`, `.relu()`, …), every const a `Tensors.*` literal, and the
 * printed gradient RUNS — bit-identical to [io.tlaloc.ir.passes.DxirInterpreter]
 * on the same inputs (the host twins and the interpreter arms are the
 * bit-equality-pinned pair the §0.4.447 audit certified).
 *
 * Typing decision (recorded): every value is declared at its HONEST ranked
 * phantom type — `DTensor<ScalarShape, F32>`, `DTensor<Rank1<Sym>, F32>`,
 * `DTensor<Rank2<Sym, Sym>, F32>`, … (`I32` for integer values) — so the
 * printed source reads like user code and the `<S : Shape>`-generic host twins
 * infer their shape parameter from the declared type or a template argument.
 * The FloatArray-level alternative was REJECTED: it reads like a code
 * generator's scratchpad, not like the Kotlin a user would write, and the
 * whole point of this surface is that the user can read their gradient.
 * Where a twin's static return type is the erased `DTensor<Shape, F32>`
 * (the axis reductions, `concat`, `.slice`), the printer wraps the call in
 * `reshapeToRankN(…, dims…)` — an identity copy that restores the ranked
 * declared type without touching a bit.
 *
 * Scope contract (LOUD, the §0.4.448 discipline): the printer either renders
 * an op as its host-twin spelling or THROWS naming the kind and the reason —
 * never a silent skip, never a plausible-looking wrong spelling. The
 * capture-route functions this serves (F1 `captureN` → `Tape.toDxirFunction`
 * → `DxirReverseTransform`) carry CONCRETE dims by construction; a -1
 * sentinel dim (the `grad {}` FIR synthesis world) is refused by name, since
 * the ranked-literal renderings below legitimately read dims off the types —
 * which is exactly what the sentinel landmine forbids doing to a sentinel.
 */
package io.tlaloc.ir.render

import io.tlaloc.core.F32
import io.tlaloc.core.I32
import io.tlaloc.core.Bool
import io.tlaloc.ir.DxirConst
import io.tlaloc.ir.DxirFunction
import io.tlaloc.ir.DxirNode
import io.tlaloc.ir.DxirOp
import io.tlaloc.ir.DxirParam
import io.tlaloc.ir.DxirType
import io.tlaloc.ir.OpKind
import io.tlaloc.ir.passes.DEMOTED_OP_KINDS
import io.tlaloc.ir.passes.demotedKindRefusal

/** Render [fn] as a complete, compilable Kotlin function. See the file KDoc. */
@kotlin.jvm.JvmName("renderKotlinSource")
fun toKotlinSource(fn: DxirFunction): String = KotlinSourceRenderer.render(fn)

/** Extension spelling of [toKotlinSource] — the user surface. */
fun DxirFunction.toKotlinSource(): String = KotlinSourceRenderer.render(this)

/** Loud refusal type: an op the printer cannot render, named. */
class KotlinRenderRefusal(message: String) : IllegalStateException(message)

internal object KotlinSourceRenderer {

    fun render(fn: DxirFunction): String {
        val names = HashMap<Int, String>(fn.params.size + fn.body.size)
        val sb = StringBuilder()
        val fnName = sanitizeIdentifier(fn.name)

        sb.appendLine("// Generated by DxirFunction.toKotlinSource() from function '${fn.name}'.")
        sb.appendLine("// Each `val` is one DXIR op, bound to its certified `:core` host-twin call;")
        sb.appendLine("// the trailing comment names the SSA node it renders.")
        sb.appendLine("import io.tlaloc.core.*")
        sb.appendLine("import io.tlaloc.core.ops.*")
        sb.appendLine()

        val paramDecls = fn.params.map { p ->
            val n = sanitizeIdentifier(p.name.ifBlank { "p${p.id}" })
            names[p.id] = n
            "$n: ${tensorType(p.type, "param ${p.name}")}"
        }
        val retTypes = fn.returns.map { tensorType(it.type, "return value") }
        val retType = when (fn.returns.size) {
            1 -> retTypes[0]
            2 -> "Pair<${retTypes[0]}, ${retTypes[1]}>"
            3 -> "Triple<${retTypes[0]}, ${retTypes[1]}, ${retTypes[2]}>"
            else -> "List<DTensor<*, *>>"
        }
        sb.appendLine("fun $fnName(${paramDecls.joinToString(", ")}): $retType {")

        for (node in fn.body) {
            when (node) {
                is DxirParam -> {} // params never appear in body
                is DxirConst -> {
                    val n = "v${node.id}"
                    names[node.id] = n
                    sb.appendLine(
                        "    val $n: ${tensorType(node.type, "const %${node.id}")} = " +
                            "${renderConst(node)} // %${node.id} = const : ${node.type}",
                    )
                }
                is DxirOp -> {
                    refuseIfUnrenderableShape(node)
                    val n = "v${node.id}"
                    names[node.id] = n
                    val rendered = renderOp(node, names)
                    val declared = tensorType(node.type, "op %${node.id} (${node.op})")
                    val rhs = if (rendered.ranked) rendered.expr else wrapToRanked(rendered.expr, node)
                    val operandRefs = node.operands.joinToString(", ") { "%${it.id}" }
                    sb.appendLine("    val $n: $declared = $rhs // %${node.id} = ${node.op}($operandRefs)")
                }
                else -> throw KotlinRenderRefusal(
                    "toKotlinSource: body node %${node.id} of kind ${node::class.simpleName} " +
                        "has no Kotlin rendering (DxirCall / block-arg forms are out of the v1 scope)",
                )
            }
        }

        val retRefs = fn.returns.map { r ->
            names[r.id] ?: throw KotlinRenderRefusal(
                "toKotlinSource: return references un-rendered node %${r.id}",
            )
        }
        val retExpr = when (retRefs.size) {
            1 -> retRefs[0]
            2 -> "Pair(${retRefs[0]}, ${retRefs[1]})"
            3 -> "Triple(${retRefs[0]}, ${retRefs[1]}, ${retRefs[2]})"
            else -> "listOf(${retRefs.joinToString(", ")})"
        }
        sb.appendLine("    return $retExpr")
        sb.appendLine("}")
        return sb.toString()
    }

    // ---------------------------------------------------------------- types

    private fun tensorType(t: DxirType, where: String): String {
        for (d in t.dims) {
            if (d < 0) {
                throw KotlinRenderRefusal(
                    "toKotlinSource: $where carries a sentinel dim in $t — the printer serves " +
                        "capture-route functions whose dims are concrete; a grad {} synthesis " +
                        "function (-1 dims) has no honest ranked-literal Kotlin rendering",
                )
            }
        }
        val dt = when (t.dtype) {
            F32 -> "F32"
            I32 -> "I32"
            // Bool rides the host mask convention: comparisons and WHERE
            // predicates are 0f/1f F32 tensors on the host surface.
            Bool -> "F32"
            // §0.4.456 (G1b) — bf16 keeps the NAMED refusal (the north-star
            // rule): the host has no bf16 kernels (compute-in-f32-store-bf16,
            // §0.4.455), so a bf16-typed reverse graph has no honest host-twin
            // spelling. The readable-reverse story for bf16 programs is the
            // f32 graph BETWEEN the precision casts; render that instead.
            else -> throw KotlinRenderRefusal(
                "toKotlinSource: $where has dtype ${t.dtype.name} — only F32/I32 (and Bool " +
                    "as the F32 mask convention) have host-twin renderings" +
                    if (t.dtype.name == "bf16") {
                        " (bf16 is storage/interchange — host math is compute-in-f32, " +
                            "so render the f32 graph between the casts, §0.4.456)"
                    } else {
                        ""
                    },
            )
        }
        val shape = when (t.rank) {
            0 -> "ScalarShape"
            1 -> "Rank1<Sym>"
            2 -> "Rank2<Sym, Sym>"
            3 -> "Rank3<Sym, Sym, Sym>"
            4 -> "Rank4<Sym, Sym, Sym, Sym>"
            else -> throw KotlinRenderRefusal(
                "toKotlinSource: $where has rank ${t.rank} — the DTensor phantom-shape " +
                    "surface spells ranks 0..4 only",
            )
        }
        return "DTensor<$shape, $dt>"
    }

    private fun sanitizeIdentifier(raw: String): String {
        val cleaned = raw.map { if (it.isLetterOrDigit() || it == '_') it else '_' }.joinToString("")
        val prefixed = if (cleaned.isEmpty() || cleaned[0].isDigit()) "fn_$cleaned" else cleaned
        return prefixed
    }

    // --------------------------------------------------------------- consts

    private fun floatLiteral(v: Float): String = when {
        v.isNaN() -> "Float.NaN"
        v == Float.POSITIVE_INFINITY -> "Float.POSITIVE_INFINITY"
        v == Float.NEGATIVE_INFINITY -> "Float.NEGATIVE_INFINITY"
        else -> "${v}f" // Float.toString is shortest-round-trip: the literal re-parses bit-exact
    }

    private fun floatArrayLiteral(a: FloatArray): String =
        "floatArrayOf(${a.joinToString(", ") { floatLiteral(it) }})"

    private fun renderConst(c: DxirConst): String {
        val t = c.type
        val v = c.value
        fun refuse(why: String): Nothing = throw KotlinRenderRefusal(
            "toKotlinSource: const %${c.id} ($why; type=$t, value ${v::class.simpleName}) " +
                "has no Tensors.* literal rendering",
        )
        return when (t.dtype) {
            F32 -> when {
                v is Float && t.isScalar -> "Tensors.f32Scalar(${floatLiteral(v)})"
                // A Float value with a SHAPED type is the transform's splat const
                // (MeanRule's 1/N at upstream shape, seed consts): fill the dims.
                v is Float -> "broadcastDims(${floatLiteral(v)}, intArrayOf(${t.dims.joinToString(", ")}))"
                v is FloatArray && t.isScalar && v.size == 1 -> "Tensors.f32Scalar(${floatLiteral(v[0])})"
                v is FloatArray && v.size == 1 && t.elementCount != 1L ->
                    "broadcastDims(${floatLiteral(v[0])}, intArrayOf(${t.dims.joinToString(", ")}))"
                v is FloatArray && v.size.toLong() == t.elementCount -> when (t.rank) {
                    1 -> "Tensors.f32Vector(${floatArrayLiteral(v)})"
                    2 -> "Tensors.f32Matrix(${t.dims[0]}, ${t.dims[1]}, ${floatArrayLiteral(v)})"
                    3 -> "Tensors.f32Tensor3(${t.dims[0]}, ${t.dims[1]}, ${t.dims[2]}, ${floatArrayLiteral(v)})"
                    4 -> "Tensors.f32Tensor4(${t.dims[0]}, ${t.dims[1]}, ${t.dims[2]}, ${t.dims[3]}, ${floatArrayLiteral(v)})"
                    else -> refuse("rank-${t.rank} F32 array const")
                }
                else -> refuse("unsupported F32 const shape")
            }
            I32 -> {
                val ints: IntArray = when (v) {
                    is IntArray -> v
                    // The tape's float-encoded integer convention (§0.4.442,
                    // exact below 2^24, asserted at trace time).
                    is FloatArray -> IntArray(v.size) { v[it].toInt() }
                    else -> refuse("I32 const value must be IntArray or float-encoded FloatArray")
                }
                when {
                    t.rank == 1 && ints.size == t.dims[0] ->
                        "Tensors.i32Vector(intArrayOf(${ints.joinToString(", ")}))"
                    t.rank == 2 && ints.size.toLong() == t.elementCount ->
                        "Tensors.i32Matrix(${t.dims[0]}, ${t.dims[1]}, intArrayOf(${ints.joinToString(", ")}))"
                    else -> refuse("I32 consts render at rank 1/2 only (no i32Scalar constructor exists)")
                }
            }
            else -> refuse("dtype ${t.dtype.name}")
        }
    }

    // ------------------------------------------------------------------ ops

    private class Rendered(val expr: String, val ranked: Boolean)

    private fun ranked(expr: String) = Rendered(expr, ranked = true)
    private fun unranked(expr: String) = Rendered(expr, ranked = false)

    /** Wrap an erased `DTensor<Shape, F32>` expression back to the declared ranked type. */
    private fun wrapToRanked(expr: String, op: DxirOp): String {
        val dims = op.type.dims
        return when (dims.size) {
            1, 2, 3, 4 -> "reshapeToRank${dims.size}($expr, ${dims.joinToString(", ")})"
            else -> throw KotlinRenderRefusal(
                "toKotlinSource: ${op.op} at %${op.id} produced an erased-shape expression at " +
                    "rank ${dims.size}, which reshapeToRank1..4 cannot restore",
            )
        }
    }

    private fun refuseIfUnrenderableShape(op: DxirOp) {
        if (op.isMultiResult) {
            throw KotlinRenderRefusal(
                "toKotlinSource: ${op.op} at %${op.id} is multi-result (${op.numResults}) — " +
                    "no Kotlin rendering in v1 (single-result SSA only)",
            )
        }
        if (op.hasRegions) {
            throw KotlinRenderRefusal(
                "toKotlinSource: ${op.op} at %${op.id} carries nested regions — structured " +
                    "control flow (IF/WHILE/COARSENED) has no Kotlin rendering in v1",
            )
        }
    }

    private fun refuse(op: DxirOp, why: String): Nothing = throw KotlinRenderRefusal(
        "toKotlinSource: ${op.op} at %${op.id} — $why",
    )

    private fun intListAttr(op: DxirOp, key: String): List<Int>? =
        (op.attrs[key] as? List<*>)?.map { (it as Number).toInt() }

    private fun intPairAttr(op: DxirOp, key: String, default: List<Int>): List<Int> {
        val l = intListAttr(op, key) ?: default
        if (l.size != 2) refuse(op, "attr '$key' must have 2 entries, got $l")
        return l
    }

    /** `padding` attr `[[top, bottom], [left, right]]` → [top, bottom, left, right]. */
    private fun paddingAttr(op: DxirOp): List<Int> {
        val raw = op.attrs["padding"] as? List<*> ?: return listOf(0, 0, 0, 0)
        val rows = raw.map { r -> (r as List<*>).map { (it as Number).toInt() } }
        if (rows.size != 2 || rows.any { it.size != 2 }) refuse(op, "attr 'padding' must be [[t,b],[l,r]], got $raw")
        return listOf(rows[0][0], rows[0][1], rows[1][0], rows[1][1])
    }

    private fun renderOp(op: DxirOp, names: Map<Int, String>): Rendered {
        fun r(i: Int): String = names[op.operands[i].id]
            ?: refuse(op, "operand %${op.operands[i].id} was not rendered before use")
        fun dims(i: Int): List<Int> = op.operands[i].type.dims
        fun requireSameShape() {
            if (dims(0) != dims(1)) {
                refuse(
                    op,
                    "operands have differing shapes ${dims(0)} vs ${dims(1)} — the host " +
                        "operators are same-shape; DXIR spells broadcasting explicitly, so this graph is malformed",
                )
            }
        }

        if (op.op in DEMOTED_OP_KINDS) {
            throw KotlinRenderRefusal(demotedKindRefusal(op.op, "toKotlinSource")!!)
        }

        return when (op.op) {
            // --- elementwise unaries: the DTensor extension twins ---
            OpKind.NEG -> ranked("${r(0)}.neg()")
            OpKind.EXP -> ranked("${r(0)}.exp()")
            OpKind.LOG -> ranked("${r(0)}.log()")
            OpKind.SQRT -> ranked("${r(0)}.sqrt()")
            OpKind.TANH -> ranked("${r(0)}.tanh()")
            OpKind.SIGMOID -> ranked("${r(0)}.sigmoid()")
            OpKind.RELU -> ranked("${r(0)}.relu()")
            OpKind.STEP -> ranked("${r(0)}.step()")
            OpKind.SIGN -> ranked("${r(0)}.sign()")
            OpKind.TAN -> ranked("${r(0)}.tan()")
            OpKind.ATAN -> ranked("${r(0)}.atan()")
            OpKind.LGAMMA -> ranked("${r(0)}.lgamma()")
            OpKind.DIGAMMA -> ranked("${r(0)}.digamma()")
            OpKind.TRIGAMMA -> ranked("${r(0)}.trigamma()")
            OpKind.POLYGAMMA -> {
                val order = (op.attrs["order"] as? Number)?.toInt()
                    ?: refuse(op, "missing integer 'order' attr")
                ranked("${r(0)}.polygamma($order)")
            }
            OpKind.ABS, OpKind.RSQRT, OpKind.GELU, OpKind.SILU, OpKind.SIN, OpKind.COS ->
                refuse(op, "no `:core` tensor host twin exists for this unary (the bmm-precedent twin gap) — add the twin, then teach the printer its spelling")
            OpKind.NOT, OpKind.LAND ->
                refuse(op, "boolean-algebra kinds have no host-twin spelling (control-flow substrate)")

            // --- elementwise binaries: the DTensor operators ---
            OpKind.ADD -> { requireSameShape(); ranked("(${r(0)} + ${r(1)})") }
            OpKind.SUB -> { requireSameShape(); ranked("(${r(0)} - ${r(1)})") }
            OpKind.MUL -> { requireSameShape(); ranked("(${r(0)} * ${r(1)})") }
            OpKind.DIV -> { requireSameShape(); ranked("(${r(0)} / ${r(1)})") }
            OpKind.POW -> { requireSameShape(); ranked("${r(0)}.pow(${r(1)})") }

            // --- reductions ---
            OpKind.SUM, OpKind.MEAN, OpKind.MAX, OpKind.MIN -> {
                val fn = op.op.name.lowercase()
                val rd = intListAttr(op, "reduction_dims") ?: emptyList()
                val inRank = op.operands[0].type.rank
                val full = rd.isEmpty() || rd.toSet() == (0 until inRank).toSet()
                if (full && op.type.isScalar) {
                    ranked("${r(0)}.$fn()")
                } else if (full) {
                    // full reduce typed keepdims: scalar reduce, reshape restores rank
                    unranked("${r(0)}.$fn()")
                } else {
                    val keep = op.type.rank == inRank
                    val args = rd.joinToString(", ") + if (keep) ", keepDims = true" else ""
                    unranked("${r(0)}.$fn($args)")
                }
            }
            OpKind.SOFTMAX -> {
                val axis = (op.attrs["axis"] as? Number)?.toInt() ?: (op.type.rank - 1)
                ranked("${r(0)}.softmax($axis)")
            }
            OpKind.ARGMAX, OpKind.LOGSUMEXP, OpKind.DOT, OpKind.CROSS_ENTROPY ->
                refuse(op, "no direct `:core` host-twin spelling wired in v1 (named deferral in docs/AD_SINGLE_ENGINE_AUDIT.md)")

            // --- linear algebra ---
            OpKind.MATMUL -> {
                if (op.operands[0].type.rank == 2 && op.operands[1].type.rank == 2) {
                    ranked("(${r(0)} matmul ${r(1)})")
                } else {
                    refuse(op, "rank-${op.operands[0].type.rank} batched matmul — `:core` has no bmm host twin (the §0.4.447 named twin-gap); render blocked until bmmGeneral lands")
                }
            }
            OpKind.CONV2D, OpKind.CONV_TRANSPOSE2D -> {
                val fgc = (op.attrs["feature_group_count"] as? Number)?.toInt() ?: 1
                val bgc = (op.attrs["batch_group_count"] as? Number)?.toInt() ?: 1
                if (fgc != 1 || bgc != 1) refuse(op, "grouped conv (fgc=$fgc, bgc=$bgc) has no host-twin spelling")
                val s = intPairAttr(op, "window_strides", listOf(1, 1))
                val l = intPairAttr(op, "lhs_dilation", listOf(1, 1))
                val d = intPairAttr(op, "rhs_dilation", listOf(1, 1))
                val p = paddingAttr(op)
                val rev = (op.attrs["window_reversal"] as? List<*>)?.map { it as Boolean } ?: listOf(false, false)
                val twin = if (op.op == OpKind.CONV2D) "conv2dGeneral" else "convTranspose2dGeneral"
                ranked(
                    "$twin(${r(0)}, ${r(1)}, ${s[0]}, ${s[1]}, ${l[0]}, ${l[1]}, ${d[0]}, ${d[1]}, " +
                        "${p[0]}, ${p[1]}, ${p[2]}, ${p[3]}, ${rev[0]}, ${rev[1]})",
                )
            }
            OpKind.CONV2D_DATA_ADJOINT, OpKind.CONV2D_KERNEL_ADJOINT -> {
                val s = intPairAttr(op, "window_strides", listOf(1, 1))
                val d = intPairAttr(op, "rhs_dilation", listOf(1, 1))
                val p = paddingAttr(op)
                val twin = if (op.op == OpKind.CONV2D_DATA_ADJOINT) "conv2dDataAdjoint" else "conv2dKernelAdjoint"
                ranked("$twin(${r(0)}, ${r(1)}, ${r(2)}, ${s[0]}, ${s[1]}, ${d[0]}, ${d[1]}, ${p[0]}, ${p[2]})")
            }
            OpKind.CONV_TRANSPOSE2D_DATA_ADJOINT, OpKind.CONV_TRANSPOSE2D_KERNEL_ADJOINT -> {
                val s = intPairAttr(op, "window_strides", listOf(1, 1))
                val l = intPairAttr(op, "lhs_dilation", listOf(1, 1))
                val d = intPairAttr(op, "rhs_dilation", listOf(1, 1))
                val p = paddingAttr(op)
                val rev = (op.attrs["window_reversal"] as? List<*>)?.map { it as Boolean } ?: listOf(false, false)
                val twin = if (op.op == OpKind.CONV_TRANSPOSE2D_DATA_ADJOINT) {
                    "convTranspose2dDataAdjoint"
                } else {
                    "convTranspose2dKernelAdjoint"
                }
                ranked(
                    "$twin(${r(0)}, ${r(1)}, ${r(2)}, ${s[0]}, ${s[1]}, ${l[0]}, ${l[1]}, ${d[0]}, ${d[1]}, " +
                        "${p[0]}, ${p[2]}, ${rev[0]}, ${rev[1]})",
                )
            }
            OpKind.MAXPOOL2D, OpKind.AVGPOOL2D -> {
                val w = intPairAttr(op, "window", listOf(1, 1))
                val s = intPairAttr(op, "window_strides", listOf(1, 1))
                val p = paddingAttr(op)
                val twin = if (op.op == OpKind.MAXPOOL2D) "maxPool2dGeneral" else "avgPool2dGeneral"
                ranked("$twin(${r(0)}, ${w[0]}, ${w[1]}, ${s[0]}, ${s[1]}, ${p[0]}, ${p[1]}, ${p[2]}, ${p[3]})")
            }
            OpKind.AVGPOOL2D_GRAD -> {
                val w = intPairAttr(op, "window", listOf(1, 1))
                val s = intPairAttr(op, "window_strides", listOf(1, 1))
                val p = paddingAttr(op)
                ranked("avgPool2dGrad(${r(0)}, ${r(1)}, ${w[0]}, ${w[1]}, ${s[0]}, ${s[1]}, ${p[0]}, ${p[2]})")
            }
            OpKind.MAXPOOL2D_GRAD -> {
                val w = intPairAttr(op, "window", listOf(1, 1))
                val s = intPairAttr(op, "window_strides", listOf(1, 1))
                val p = paddingAttr(op)
                ranked("maxPool2dGrad(${r(0)}, ${r(1)}, ${r(2)}, ${w[0]}, ${w[1]}, ${s[0]}, ${s[1]}, ${p[0]}, ${p[2]})")
            }

            // --- shape ---
            OpKind.RESHAPE -> when (op.type.rank) {
                1, 2, 3, 4 -> ranked("reshapeToRank${op.type.rank}(${r(0)}, ${op.type.dims.joinToString(", ")})")
                else -> refuse(op, "reshape to rank ${op.type.rank} has no reshapeToRankN twin (rank 1..4 only)")
            }
            OpKind.TRANSPOSE -> {
                val perm = intListAttr(op, "permutation")?.ifEmpty { null }
                    ?: (op.type.rank - 1 downTo 0).toList()
                when (perm.size) {
                    2, 3, 4 -> ranked("transposePerm${perm.size}(${r(0)}, ${perm.joinToString(", ")})")
                    else -> refuse(op, "rank-${perm.size} transpose has no transposePermN twin (rank 2..4 only)")
                }
            }
            OpKind.BROADCAST -> {
                if (op.operands.size != 1) {
                    refuse(op, "the template-carrying BROADCAST form is sentinel-only; capture-route graphs carry concrete dims")
                }
                val bd = intListAttr(op, "broadcast_dimensions") ?: emptyList()
                val inDims = dims(0)
                val outDims = op.type.dims
                val outArgs = outDims.joinToString(", ")
                when {
                    outDims.size !in 1..3 ->
                        refuse(op, "broadcast to rank ${outDims.size} — stretchToRank1..3 are the only stretch twins")
                    bd.isEmpty() && inDims.isEmpty() ->
                        // scalar splat: reshape to all-ones keepdims, stretch to target
                        ranked("stretchToRank${outDims.size}(${r(0)}.reshape(${outDims.map { 1 }.joinToString(", ")}), $outArgs)")
                    bd.isEmpty() && inDims.size == outDims.size ->
                        // equal-rank keepdims stretch
                        ranked("stretchToRank${outDims.size}(${r(0)}, $outArgs)")
                    bd.isNotEmpty() && bd == bd.sorted() && bd.size == inDims.size -> {
                        // broadcast_in_dim with sorted dims: place input axes at their
                        // output positions (1s elsewhere), then stretch.
                        val placed = IntArray(outDims.size) { 1 }
                        for ((j, axis) in bd.withIndex()) placed[axis] = inDims[j]
                        ranked("stretchToRank${outDims.size}(${r(0)}.reshape(${placed.joinToString(", ")}), $outArgs)")
                    }
                    else -> refuse(op, "broadcast_dimensions=$bd (unsorted or arity-mismatched) has no reshape+stretch spelling")
                }
            }
            OpKind.CONCAT -> {
                val axis = (op.attrs["dimension"] as? Number)?.toInt() ?: 0
                unranked("concat($axis, ${op.operands.indices.joinToString(", ") { r(it) }})")
            }
            OpKind.SLICE -> {
                val starts = intListAttr(op, "start_indices") ?: refuse(op, "missing 'start_indices' attr")
                val limits = intListAttr(op, "limit_indices") ?: refuse(op, "missing 'limit_indices' attr")
                val strides = intListAttr(op, "strides") ?: List(starts.size) { 1 }
                if (strides.any { it != 1 }) refuse(op, "strided slice (strides=$strides) has no host-twin spelling")
                var expr = r(0)
                var sliced = false
                for (axis in starts.indices) {
                    if (starts[axis] != 0 || limits[axis] != dims(0)[axis]) {
                        expr = "$expr.slice(${starts[axis]}, ${limits[axis]}, $axis)"
                        sliced = true
                    }
                }
                if (sliced) unranked(expr) else unranked("$expr.reshape(${op.type.dims.joinToString(", ")})")
            }
            OpKind.REVERSE -> {
                val axes = intListAttr(op, "dimensions") ?: refuse(op, "missing 'dimensions' attr")
                ranked("${r(0)}.flip(${axes.joinToString(", ")})")
            }
            OpKind.GATHER, OpKind.SCATTER, OpKind.SCATTER_ADD ->
                refuse(op, "the scalar-index gather/scatter family reads a runtime index operand `:core`'s Int-taking twins cannot express (named deferral in docs/AD_SINGLE_ENGINE_AUDIT.md)")
            OpKind.PAD ->
                refuse(op, "standalone PAD has no host twin (the transform emits PAD_TO, which renders as padToLike); named deferral")

            // --- runtime-extent family: template-carrying twins ---
            OpKind.SUM_TO -> ranked("sumToLike(${r(0)}, ${r(1)})")
            OpKind.BROADCAST_LIKE -> ranked("broadcastToLike(${r(0)}, ${r(1)})")
            OpKind.PAD_TO -> {
                val low = intListAttr(op, "low") ?: refuse(op, "missing 'low' attr")
                ranked("padToLike(${r(0)}, ${r(1)}, intArrayOf(${low.joinToString(", ")}))")
            }
            OpKind.SLICE_AT -> {
                val low = intListAttr(op, "low") ?: refuse(op, "missing 'low' attr")
                ranked("sliceAtLike(${r(0)}, ${r(1)}, intArrayOf(${low.joinToString(", ")}))")
            }
            OpKind.SLICE_LIKE, OpKind.PAD_LIKE -> {
                val axis = (op.attrs["axis"] as? Number)?.toInt() ?: refuse(op, "missing 'axis' attr")
                val priors = op.operands.size - 2
                val base = if (op.op == OpKind.SLICE_LIKE) "sliceLike" else "padLike"
                when {
                    priors == 0 -> ranked("${base}Start(${r(0)}, ${r(1)}, $axis)")
                    priors in 1..7 -> {
                        val priorRefs = (2 until op.operands.size).joinToString(", ") { r(it) }
                        ranked("${base}After$priors(${r(0)}, ${r(1)}, $priorRefs, $axis)")
                    }
                    else -> refuse(op, "$priors prior templates exceed the After1..7 twin family")
                }
            }
            OpKind.ZEROS_LIKE -> when (op.operands[0].type.dtype) {
                I32 -> ranked("intZerosLike(${r(0)})")
                F32 -> ranked("broadcastLike(0.0f, ${r(0)})")
                else -> refuse(op, "ZEROS_LIKE over dtype ${op.operands[0].type.dtype.name}")
            }
            OpKind.CHECK_SHAPE_LIKE -> ranked("checkShapeLike(${r(0)}, ${r(1)})")

            // --- select / compare / cast ---
            OpKind.WHERE -> ranked("where(${r(0)}, ${r(1)}, ${r(2)})")
            OpKind.COMPARE -> {
                val dir = op.attrs["direction"] as? String ?: refuse(op, "missing 'direction' attr")
                val infix = when (dir) {
                    "EQ" -> "eq"; "NE" -> "ne"; "LT" -> "lt"; "LE" -> "le"; "GT" -> "gt"; "GE" -> "ge"
                    else -> refuse(op, "unknown compare direction '$dir'")
                }
                requireSameShape()
                ranked("(${r(0)} $infix ${r(1)})")
            }
            OpKind.CAST -> {
                val src = op.operands[0].type.dtype
                val dst = op.type.dtype
                val identityOnHost =
                    (src == Bool && dst == F32) || (src == F32 && dst == Bool) || src == dst
                if (identityOnHost) {
                    // value-domain identity (the Bool 0f/1f mask convention)
                    ranked(r(0))
                } else {
                    refuse(op, "cast ${src.name} -> ${dst.name} has no host-twin spelling (only the Bool<->F32 mask identity renders)")
                }
            }

            // --- embedding ---
            OpKind.EMBEDDING -> {
                val pi = (op.attrs["padding_index"] as? Int) ?: -1
                if (pi >= 0) ranked("embedding(${r(0)}, ${r(1)}, $pi)") else ranked("embedding(${r(0)}, ${r(1)})")
            }
            OpKind.EMBEDDING_GRAD -> {
                // IR operand order (indices, upstream, tableTemplate); host twin
                // takes (upstream, indices, tableTemplate[, paddingIndex]).
                val pi = (op.attrs["padding_index"] as? Int) ?: -1
                if (pi >= 0) {
                    ranked("embeddingGrad(${r(1)}, ${r(0)}, ${r(2)}, $pi)")
                } else {
                    ranked("embeddingGrad(${r(1)}, ${r(0)}, ${r(2)})")
                }
            }

            // --- RNG: literal-key rank-1/2 draws only ---
            OpKind.RNG_UNIFORM, OpKind.RNG_NORMAL -> {
                if (op.operands.isNotEmpty()) refuse(op, "the runtime-key operand form has no host-twin spelling (the rng* twins take literal key words)")
                val k0 = (op.attrs["key0"] as? Number)?.toInt() ?: refuse(op, "missing 'key0' attr")
                val k1 = (op.attrs["key1"] as? Number)?.toInt() ?: refuse(op, "missing 'key1' attr")
                val base = if (op.op == OpKind.RNG_UNIFORM) "rngUniform" else "rngNormal"
                when (op.type.rank) {
                    1 -> ranked("${base}Vector($k0, $k1, ${op.type.dims[0]})")
                    2 -> ranked("${base}Matrix($k0, $k1, ${op.type.dims[0]}, ${op.type.dims[1]})")
                    else -> refuse(op, "rank-${op.type.rank} draw — rng*Vector/Matrix are the only twins")
                }
            }

            OpKind.SPARSE_MATMUL, OpKind.SPARSE_MATMUL_VALUES_ADJOINT ->
                refuse(op, "the CSR-component sparse family is host-twin-backed but not yet wired into the printer (named deferral in docs/AD_SINGLE_ENGINE_AUDIT.md)")
            OpKind.RMSNORM, OpKind.BATCHNORM ->
                refuse(op, "the norm kinds ride their desugared op compositions (§0.4.390); the fused kinds have no printed spelling")

            // --- control flow / structural: no rendering by design ---
            OpKind.IF, OpKind.WHILE, OpKind.COARSENED ->
                refuse(op, "structured control flow has no straight-line Kotlin rendering in v1")
            OpKind.MANUAL_COMPUTATION, OpKind.ALL_GATHER, OpKind.REDUCE_SCATTER ->
                refuse(op, "sharding/collective kinds are emission-layer constructs with no host spelling")

            // §0.4.460 — Phase G3a: ALL_REDUCE is differentiable now, but it
            // keeps a NAMED refusal here: the readable reverse of a collective
            // program is its PER-REPLICA local source, and rendering the
            // interpreter's single-process ×|group| convention would bake a
            // distribution fact (the group size) into host math as a literal —
            // the sentinel-dims class of mistake. Execution semantics arrive
            // with G2b/G4.
            OpKind.ALL_REDUCE ->
                refuse(
                    op,
                    "ALL_REDUCE has no single-process host spelling — the readable reverse " +
                        "of a collective program is its per-replica local source; the " +
                        "interpreter's ×|group| unit semantics are an SPMD modelling " +
                        "convention, not host math (§0.4.460 G3a; G2b/G4 own execution)",
                )

            // §0.4.460 — Phase G3a: SHARD_CONSTRAINT is a value identity with
            // layout metadata; the host rendering is the pass-through (the
            // metadata has no host-math meaning and is deliberately dropped).
            OpKind.SHARD_CONSTRAINT -> ranked(r(0))

            // Demoted kinds: handled above by demotedKindRefusal, but the `when`
            // stays exhaustive so a NEW OpKind fails compilation right here.
            OpKind.LAYERNORM, OpKind.SCALED_DOT_PRODUCT_ATTENTION,
            -> throw KotlinRenderRefusal(demotedKindRefusal(op.op, "toKotlinSource")!!)
        }
    }
}
