package io.tlaloc.kptx

/**
 * KPTX v2.7 (§0.4.344) — the production kernel library (plan task 15):
 * the v1 hand-written kernels rewritten as [PtxKernelTemplate]s. This
 * file is now the **single source** for the KPTX rms_norm family — the
 * runtime/benchmark tests register `specialize(...).emitPtx()` output
 * instead of hand-written strings, so the same GPU tests that pinned
 * the v1 texts (§0.4.335/336 oracles + E2E) re-certify these
 * transcriptions numerically on every run.
 *
 * The symbolic `block` shape sizes the shared-memory reduction scratch
 * (`4·block` bytes per array) — the v1 texts hard-coded 1024 for the
 * 256-thread launch; specializing at another block size now emits a
 * consistent kernel instead of a silent smem overflow.
 *
 * Emitted text is canonical from birth: byte-stable under parse/emit
 * (the v2 DoD) and ISA-clean by construction (every `inst()` was
 * validated at build time). The §0.4.328–336 hand-written texts remain
 * in [PtxRoundTripCorpus] as historical parser fixtures.
 */
object KptxKernels {

    /**
     * RMS-norm forward, eps-operand variant — the kernel the
     * [io.tlaloc.ir.recognizer.kernel] RmsNormKernel template claims as
     * `custom_call @kptx_rms_norm(x, eps[rows,1]) -> y` (§0.4.336).
     * One CTA per token row, `block` threads: strided fma
     * sum-of-squares, shared-memory tree reduction, `sqrt.rn`+`rcp.rn`
     * normalizer, strided `out = x · r` writes. Launch signature:
     * `(x_ptr, eps_ptr, out_ptr, n_cols)` — n_cols stays a runtime
     * scalar (the registry's trailing-i32 marshalling, §0.4.330).
     */
    val rmsNormEps: PtxKernelTemplate = PtxKernelTemplate("kptx_rms_norm") { env ->
        val block = env.shape("block")
        val xPtr = param(".u64", "x_ptr")
        val epsPtr = param(".u64", "eps_ptr")
        val outPtr = param(".u64", "out_ptr")
        val nColsP = param(".u32", "n_cols")

        val p1 = pred(); val p2 = pred(); val p3 = pred()
        val r = List(9) { r32() }                       // %r1..%r9
        val f = List(14) { f32() }                      // %f1..%f14
        val rd = List(21) { r64() }                     // %rd1..%rd21
        val sdata = shared("sdata", sizeBytes = 4 * block)

        inst("ld.param.u64", rd[0], mem(xPtr))
        inst("ld.param.u64", rd[1], mem(epsPtr))
        inst("ld.param.u64", rd[2], mem(outPtr))
        inst("ld.param.u32", r[0], mem(nColsP))
        inst("cvta.to.global.u64", rd[3], rd[0])
        inst("cvta.to.global.u64", rd[4], rd[1])
        inst("cvta.to.global.u64", rd[5], rd[2])
        blank()
        inst("mov.u32", r[1], ctaidX)
        inst("mov.u32", r[2], tidX)
        inst("mov.u32", r[3], ntidX)
        blank()
        comment("row base byte offset = row * n_cols * 4")
        inst("mul.lo.u32", r[4], r[1], r[0])
        inst("mul.wide.u32", rd[6], r[4], imm(4))
        inst("add.s64", rd[7], rd[3], rd[6])
        inst("add.s64", rd[8], rd[5], rd[6])
        blank()
        comment("strided sum of squares")
        inst("mov.f32", f[0], imm("0f00000000"))
        inst("mov.u32", r[5], r[2])
        val loopSum = label("LOOP_SUM")
        val sumDone = label("SUM_DONE")
        place(loopSum)
        inst("setp.ge.u32", p1, r[5], r[0])
        inst("bra", sumDone, guard = p1)
        inst("mul.wide.u32", rd[9], r[5], imm(4))
        inst("add.s64", rd[10], rd[7], rd[9])
        inst("ld.global.f32", f[1], mem(rd[10]))
        inst("fma.rn.f32", f[0], f[1], f[1], f[0])
        inst("add.u32", r[5], r[5], r[3])
        inst("bra", loopSum)
        place(sumDone)
        blank()
        inst("mul.wide.u32", rd[11], r[2], imm(4))
        inst("mov.u64", rd[12], sdata)
        inst("add.s64", rd[13], rd[12], rd[11])
        inst("st.shared.f32", mem(rd[13]), f[0])
        inst("bar.sync", imm(0))
        blank()
        comment("shared-memory tree reduction: stride = ntid/2 .. 1")
        inst("shr.u32", r[6], r[3], imm(1))
        val redLoop = label("RED_LOOP")
        val redSkip = label("RED_SKIP")
        val redDone = label("RED_DONE")
        place(redLoop)
        inst("setp.eq.u32", p2, r[6], imm(0))
        inst("bra", redDone, guard = p2)
        inst("setp.ge.u32", p3, r[2], r[6])
        inst("bra", redSkip, guard = p3)
        inst("add.u32", r[7], r[2], r[6])
        inst("mul.wide.u32", rd[14], r[7], imm(4))
        inst("add.s64", rd[15], rd[12], rd[14])
        inst("ld.shared.f32", f[2], mem(rd[15]))
        inst("ld.shared.f32", f[3], mem(rd[13]))
        inst("add.f32", f[4], f[2], f[3])
        inst("st.shared.f32", mem(rd[13]), f[4])
        place(redSkip)
        inst("bar.sync", imm(0))
        inst("shr.u32", r[6], r[6], imm(1))
        inst("bra", redLoop)
        place(redDone)
        blank()
        comment("inv_rms = 1 / sqrt(sum/n + eps[row]); eps is the coarsener's")
        comment("[rows, 1] operand, one value per token row")
        inst("ld.shared.f32", f[5], mem(rd[12]))
        inst("cvt.rn.f32.u32", f[6], r[0])
        inst("div.rn.f32", f[7], f[5], f[6])
        inst("mul.wide.u32", rd[16], r[1], imm(4))
        inst("add.s64", rd[17], rd[4], rd[16])
        inst("ld.global.f32", f[8], mem(rd[17]))
        inst("add.f32", f[9], f[7], f[8])
        inst("sqrt.rn.f32", f[10], f[9])
        inst("rcp.rn.f32", f[11], f[10])
        blank()
        comment("strided write: out = x * inv_rms")
        inst("mov.u32", r[8], r[2])
        val loopOut = label("LOOP_OUT")
        val outDone = label("OUT_DONE")
        place(loopOut)
        inst("setp.ge.u32", p1, r[8], r[0])
        inst("bra", outDone, guard = p1)
        inst("mul.wide.u32", rd[18], r[8], imm(4))
        inst("add.s64", rd[19], rd[7], rd[18])
        inst("ld.global.f32", f[12], mem(rd[19]))
        inst("mul.f32", f[13], f[12], f[11])
        inst("add.s64", rd[20], rd[8], rd[18])
        inst("st.global.f32", mem(rd[20]), f[13])
        inst("add.u32", r[8], r[8], r[3])
        inst("bra", loopOut)
        place(outDone)
        inst("ret")
    }

    /**
     * RMS-norm backward, dx half (§0.4.335 math): with
     * `r = 1/sqrt(mean(x²)+eps)`, `s = Σ dy·w·x`, computes
     * `dx = (dy·w)·r − x·r³·s/D` and writes `inv_rms[row] = r` for the
     * dw kernel to consume. One CTA per row, dual shared-memory tree
     * (two `4·block`-byte arrays). Launch signature:
     * `(x_ptr, w_ptr, dy_ptr, dx_ptr, invr_ptr, n_cols)`.
     */
    val rmsNormBwdDx: PtxKernelTemplate = PtxKernelTemplate("kptx_rms_norm_bwd_dx") { env ->
        val block = env.shape("block")
        val xPtr = param(".u64", "x_ptr")
        val wPtr = param(".u64", "w_ptr")
        val dyPtr = param(".u64", "dy_ptr")
        val dxPtr = param(".u64", "dx_ptr")
        val invrPtr = param(".u64", "invr_ptr")
        val nColsP = param(".u32", "n_cols")

        val p1 = pred(); val p2 = pred(); val p3 = pred(); val p4 = pred(); val p5 = pred()
        val r = List(9) { r32() }
        val f = List(30) { f32() }
        val rd = List(33) { r64() }
        val sdata = shared("sdata", sizeBytes = 4 * block)
        val sdata2 = shared("sdata2", sizeBytes = 4 * block)

        inst("ld.param.u64", rd[0], mem(xPtr))
        inst("ld.param.u64", rd[1], mem(wPtr))
        inst("ld.param.u64", rd[2], mem(dyPtr))
        inst("ld.param.u64", rd[3], mem(dxPtr))
        inst("ld.param.u64", rd[4], mem(invrPtr))
        inst("ld.param.u32", r[0], mem(nColsP))
        inst("cvta.to.global.u64", rd[5], rd[0])
        inst("cvta.to.global.u64", rd[6], rd[1])
        inst("cvta.to.global.u64", rd[7], rd[2])
        inst("cvta.to.global.u64", rd[8], rd[3])
        inst("cvta.to.global.u64", rd[9], rd[4])
        blank()
        inst("mov.u32", r[1], ctaidX)
        inst("mov.u32", r[2], tidX)
        inst("mov.u32", r[3], ntidX)
        blank()
        comment("row base byte offset = row * n_cols * 4")
        inst("mul.lo.u32", r[4], r[1], r[0])
        inst("mul.wide.u32", rd[10], r[4], imm(4))
        inst("add.s64", rd[11], rd[5], rd[10], comment = "x row")
        inst("add.s64", rd[12], rd[7], rd[10], comment = "dy row")
        inst("add.s64", rd[13], rd[8], rd[10], comment = "dx row")
        blank()
        comment("strided accumulate: sumsq += x*x ; s += (dy*w)*x")
        inst("mov.f32", f[0], imm("0f00000000"))
        inst("mov.f32", f[1], imm("0f00000000"))
        inst("mov.u32", r[5], r[2])
        val loopAcc = label("LOOP_ACC")
        val accDone = label("ACC_DONE")
        place(loopAcc)
        inst("setp.ge.u32", p1, r[5], r[0])
        inst("bra", accDone, guard = p1)
        inst("mul.wide.u32", rd[14], r[5], imm(4))
        inst("add.s64", rd[15], rd[11], rd[14])
        inst("ld.global.f32", f[2], mem(rd[15]))
        inst("add.s64", rd[16], rd[12], rd[14])
        inst("ld.global.f32", f[3], mem(rd[16]))
        inst("add.s64", rd[17], rd[6], rd[14])
        inst("ld.global.f32", f[4], mem(rd[17]))
        inst("fma.rn.f32", f[0], f[2], f[2], f[0])
        inst("mul.f32", f[5], f[3], f[4])
        inst("fma.rn.f32", f[1], f[5], f[2], f[1])
        inst("add.u32", r[5], r[5], r[3])
        inst("bra", loopAcc)
        place(accDone)
        blank()
        comment("sdata[tid] = sumsq partial, sdata2[tid] = s partial")
        inst("mul.wide.u32", rd[18], r[2], imm(4))
        inst("mov.u64", rd[19], sdata)
        inst("add.s64", rd[20], rd[19], rd[18])
        inst("st.shared.f32", mem(rd[20]), f[0])
        inst("mov.u64", rd[21], sdata2)
        inst("add.s64", rd[22], rd[21], rd[18])
        inst("st.shared.f32", mem(rd[22]), f[1])
        inst("bar.sync", imm(0))
        blank()
        comment("dual shared-memory tree reduction: stride = ntid/2 .. 1")
        inst("shr.u32", r[6], r[3], imm(1))
        val redLoop = label("RED_LOOP")
        val redSkip = label("RED_SKIP")
        val redDone = label("RED_DONE")
        place(redLoop)
        inst("setp.eq.u32", p2, r[6], imm(0))
        inst("bra", redDone, guard = p2)
        inst("setp.ge.u32", p3, r[2], r[6])
        inst("bra", redSkip, guard = p3)
        inst("add.u32", r[7], r[2], r[6])
        inst("mul.wide.u32", rd[23], r[7], imm(4))
        inst("add.s64", rd[24], rd[19], rd[23])
        inst("ld.shared.f32", f[6], mem(rd[24]))
        inst("ld.shared.f32", f[7], mem(rd[20]))
        inst("add.f32", f[8], f[6], f[7])
        inst("st.shared.f32", mem(rd[20]), f[8])
        inst("add.s64", rd[25], rd[21], rd[23])
        inst("ld.shared.f32", f[9], mem(rd[25]))
        inst("ld.shared.f32", f[10], mem(rd[22]))
        inst("add.f32", f[11], f[9], f[10])
        inst("st.shared.f32", mem(rd[22]), f[11])
        place(redSkip)
        inst("bar.sync", imm(0))
        inst("shr.u32", r[6], r[6], imm(1))
        inst("bra", redLoop)
        place(redDone)
        blank()
        comment("r = 1/sqrt(sumsq/n + eps); c = r^3 * (s/n)")
        inst("ld.shared.f32", f[12], mem(rd[19]))
        inst("ld.shared.f32", f[13], mem(rd[21]))
        inst("cvt.rn.f32.u32", f[14], r[0])
        inst("div.rn.f32", f[15], f[12], f[14])
        inst("add.f32", f[16], f[15], imm("0f3727C5AC"))
        inst("sqrt.rn.f32", f[17], f[16])
        inst("rcp.rn.f32", f[18], f[17])
        inst("mul.f32", f[19], f[18], f[18])
        inst("mul.f32", f[20], f[19], f[18])
        inst("div.rn.f32", f[21], f[13], f[14])
        inst("mul.f32", f[22], f[20], f[21])
        blank()
        comment("thread 0 writes inv_rms[row]")
        val skipInvr = label("SKIP_INVR")
        inst("setp.ne.u32", p4, r[2], imm(0))
        inst("bra", skipInvr, guard = p4)
        inst("mul.wide.u32", rd[26], r[1], imm(4))
        inst("add.s64", rd[27], rd[9], rd[26])
        inst("st.global.f32", mem(rd[27]), f[18])
        place(skipInvr)
        blank()
        comment("strided write: dx = (dy*w)*r - x*c")
        inst("mov.u32", r[8], r[2])
        val loopOut = label("LOOP_OUT")
        val outDone = label("OUT_DONE")
        place(loopOut)
        inst("setp.ge.u32", p5, r[8], r[0])
        inst("bra", outDone, guard = p5)
        inst("mul.wide.u32", rd[28], r[8], imm(4))
        inst("add.s64", rd[29], rd[11], rd[28])
        inst("ld.global.f32", f[23], mem(rd[29]))
        inst("add.s64", rd[30], rd[12], rd[28])
        inst("ld.global.f32", f[24], mem(rd[30]))
        inst("add.s64", rd[31], rd[6], rd[28])
        inst("ld.global.f32", f[25], mem(rd[31]))
        inst("mul.f32", f[26], f[24], f[25])
        inst("mul.f32", f[27], f[26], f[18])
        inst("mul.f32", f[28], f[23], f[22])
        inst("sub.f32", f[29], f[27], f[28])
        inst("add.s64", rd[32], rd[13], rd[28])
        inst("st.global.f32", mem(rd[32]), f[29])
        inst("add.u32", r[8], r[8], r[3])
        inst("bra", loopOut)
        place(outDone)
        inst("ret")
    }

    /**
     * §0.4.349 — RoPE forward, the recognizer's SUB-form/cos-first
     * recombination (the LlamaDecoder shape):
     * `out = x_real·cos(θ) − x_imag·sin(θ)`, elementwise. Grid-stride
     * one-thread-per-element; `n` (total elements) stays a runtime
     * trailing-i32 scalar. Uses PTX's `cos.approx`/`sin.approx` — the
     * only sin/cos PTX offers; at RoPE's angle magnitudes the approx
     * error is ~1e-6 absolute, pinned against the XLA oracle by
     * KptxRopeKernelTest. Launch signature:
     * `(x_real_ptr, x_imag_ptr, theta_ptr, out_ptr, n)`.
     */
    val rope: PtxKernelTemplate = PtxKernelTemplate("kptx_rope") { _ ->
        val xrPtr = param(".u64", "x_real_ptr")
        val xiPtr = param(".u64", "x_imag_ptr")
        val thPtr = param(".u64", "theta_ptr")
        val outPtr = param(".u64", "out_ptr")
        val nP = param(".u32", "n")

        val p1 = pred()
        val r = List(6) { r32() }
        val f = List(8) { f32() }
        val rd = List(13) { r64() }

        inst("ld.param.u64", rd[0], mem(xrPtr))
        inst("ld.param.u64", rd[1], mem(xiPtr))
        inst("ld.param.u64", rd[2], mem(thPtr))
        inst("ld.param.u64", rd[3], mem(outPtr))
        inst("ld.param.u32", r[0], mem(nP))
        inst("cvta.to.global.u64", rd[4], rd[0])
        inst("cvta.to.global.u64", rd[5], rd[1])
        inst("cvta.to.global.u64", rd[6], rd[2])
        inst("cvta.to.global.u64", rd[7], rd[3])
        blank()
        comment("element index = ctaid * ntid + tid; guard idx < n")
        inst("mov.u32", r[1], ctaidX)
        inst("mov.u32", r[2], ntidX)
        inst("mov.u32", r[3], tidX)
        inst("mad.lo.u32", r[4], r[1], r[2], r[3])
        val done = label("DONE")
        inst("setp.ge.u32", p1, r[4], r[0])
        inst("bra", done, guard = p1)
        blank()
        comment("out = x_real*cos(theta) - x_imag*sin(theta)")
        inst("mul.wide.u32", rd[8], r[4], imm(4))
        inst("add.s64", rd[9], rd[6], rd[8])
        inst("ld.global.f32", f[0], mem(rd[9]), comment = "theta")
        inst("cos.approx.f32", f[1], f[0])
        inst("sin.approx.f32", f[2], f[0])
        inst("add.s64", rd[10], rd[4], rd[8])
        inst("ld.global.f32", f[3], mem(rd[10]), comment = "x_real")
        inst("add.s64", rd[11], rd[5], rd[8])
        inst("ld.global.f32", f[4], mem(rd[11]), comment = "x_imag")
        inst("mul.f32", f[5], f[3], f[1])
        inst("mul.f32", f[6], f[4], f[2])
        inst("sub.f32", f[7], f[5], f[6])
        inst("add.s64", rd[12], rd[7], rd[8])
        inst("st.global.f32", mem(rd[12]), f[7])
        place(done)
        inst("ret")
    }

    /**
     * §0.4.350 — CrossEntropy forward as a **two-stage launch chain**
     * behind one custom_call: the coarsened CE returns a scalar
     * (`loss = Σ_ij labels·log(softmax(logits))`, labels-left, full
     * reduction), which needs a cross-row stage; the intermediate
     * `row_loss[rows]` lives in an extra XLA-owned custom_call result
     * (never handler-allocated scratch), and the registry launches both
     * stages back-to-back on XLA's stream.
     *
     * Stage 1, `kptx_cross_entropy_rows(logits, labels, row_loss,
     * n_cols)` — one CTA per row: strided max reduction, then one
     * strided pass accumulating (Σ exp(l−max), Σ lab·(l−max), Σ lab)
     * into a triple shared-memory tree; thread 0 writes
     * `row_loss = Σ lab·(l−max) − (Σ lab)·ln(Σ exp(l−max))` — the exact
     * algebra of the emitter's max-subtracting softmax → log → mul →
     * sum decomposition. Natural exp/log via the approx-only PTX
     * transcendentals: `ex2(x·log2e)`, `lg2(x)·ln2` (hex-spelled
     * constants; grade pinned vs the XLA oracle).
     *
     * Stage 2, `kptx_cross_entropy_sum(row_loss, loss, n_rows)` — one
     * CTA, strided sum + tree, thread 0 writes the scalar.
     */
    /* Multi-kernel modules come from [ptxModule]; [PtxKernelTemplate]
     * is single-kernel, so the CE chain is cached here by block size. */
    private val ceCache = HashMap<Int, PtxModule>()

    fun crossEntropyModule(block: Int): PtxModule = ceCache.getOrPut(block) {
        // log2(e) = 0x3FB8AA3B, ln(2) = 0x3F317218 (f32, bit-exact).
        ptxModule {
            kernel("kptx_cross_entropy_rows") {
                val logitsPtr = param(".u64", "logits_ptr")
                val labelsPtr = param(".u64", "labels_ptr")
                val rowLossPtr = param(".u64", "row_loss_ptr")
                val nColsP = param(".u32", "n_cols")

                val p1 = pred(); val p2 = pred(); val p3 = pred(); val p4 = pred()
                val r = List(8) { r32() }
                val f = List(20) { f32() }
                val rd = List(20) { r64() }
                val smax = shared("smax", sizeBytes = 4 * block)
                val ssum = shared("ssum", sizeBytes = 4 * block)
                val sdot = shared("sdot", sizeBytes = 4 * block)
                val slab = shared("slab", sizeBytes = 4 * block)

                inst("ld.param.u64", rd[0], mem(logitsPtr))
                inst("ld.param.u64", rd[1], mem(labelsPtr))
                inst("ld.param.u64", rd[2], mem(rowLossPtr))
                inst("ld.param.u32", r[0], mem(nColsP))
                inst("cvta.to.global.u64", rd[3], rd[0])
                inst("cvta.to.global.u64", rd[4], rd[1])
                inst("cvta.to.global.u64", rd[5], rd[2])
                blank()
                inst("mov.u32", r[1], ctaidX)
                inst("mov.u32", r[2], tidX)
                inst("mov.u32", r[3], ntidX)
                comment("row bases")
                inst("mul.lo.u32", r[4], r[1], r[0])
                inst("mul.wide.u32", rd[6], r[4], imm(4))
                inst("add.s64", rd[7], rd[3], rd[6], comment = "logits row")
                inst("add.s64", rd[8], rd[4], rd[6], comment = "labels row")
                blank()
                comment("pass 1: strided row max")
                inst("mov.f32", f[0], imm("0fFF800000"), comment = "-inf")
                inst("mov.u32", r[5], r[2])
                val maxLoop = label("MAX_LOOP")
                val maxDone = label("MAX_DONE")
                place(maxLoop)
                inst("setp.ge.u32", p1, r[5], r[0])
                inst("bra", maxDone, guard = p1)
                inst("mul.wide.u32", rd[9], r[5], imm(4))
                inst("add.s64", rd[10], rd[7], rd[9])
                inst("ld.global.f32", f[1], mem(rd[10]))
                inst("max.f32", f[0], f[0], f[1])
                inst("add.u32", r[5], r[5], r[3])
                inst("bra", maxLoop)
                place(maxDone)
                inst("mul.wide.u32", rd[11], r[2], imm(4))
                inst("mov.u64", rd[12], smax)
                inst("add.s64", rd[13], rd[12], rd[11])
                inst("st.shared.f32", mem(rd[13]), f[0])
                inst("bar.sync", imm(0))
                comment("max tree")
                inst("shr.u32", r[6], r[3], imm(1))
                val mredLoop = label("MRED_LOOP")
                val mredSkip = label("MRED_SKIP")
                val mredDone = label("MRED_DONE")
                place(mredLoop)
                inst("setp.eq.u32", p2, r[6], imm(0))
                inst("bra", mredDone, guard = p2)
                inst("setp.ge.u32", p3, r[2], r[6])
                inst("bra", mredSkip, guard = p3)
                inst("add.u32", r[7], r[2], r[6])
                inst("mul.wide.u32", rd[14], r[7], imm(4))
                inst("add.s64", rd[15], rd[12], rd[14])
                inst("ld.shared.f32", f[2], mem(rd[15]))
                inst("ld.shared.f32", f[3], mem(rd[13]))
                inst("max.f32", f[4], f[2], f[3])
                inst("st.shared.f32", mem(rd[13]), f[4])
                place(mredSkip)
                inst("bar.sync", imm(0))
                inst("shr.u32", r[6], r[6], imm(1))
                inst("bra", mredLoop)
                place(mredDone)
                inst("ld.shared.f32", f[5], mem(rd[12]), comment = "row max")
                inst("bar.sync", imm(0))
                blank()
                comment("pass 2: strided (sum exp(l-max), sum lab*(l-max), sum lab)")
                inst("mov.f32", f[6], imm("0f00000000"))
                inst("mov.f32", f[7], imm("0f00000000"))
                inst("mov.f32", f[8], imm("0f00000000"))
                inst("mov.u32", r[5], r[2])
                val accLoop = label("ACC_LOOP")
                val accDone = label("ACC_DONE")
                place(accLoop)
                inst("setp.ge.u32", p1, r[5], r[0])
                inst("bra", accDone, guard = p1)
                inst("mul.wide.u32", rd[9], r[5], imm(4))
                inst("add.s64", rd[10], rd[7], rd[9])
                inst("ld.global.f32", f[9], mem(rd[10]), comment = "logit")
                inst("add.s64", rd[16], rd[8], rd[9])
                inst("ld.global.f32", f[10], mem(rd[16]), comment = "label")
                inst("sub.f32", f[11], f[9], f[5], comment = "l - max")
                inst("mul.f32", f[12], f[11], imm("0f3FB8AA3B"), comment = "* log2(e)")
                inst("ex2.approx.f32", f[13], f[12])
                inst("add.f32", f[6], f[6], f[13])
                inst("fma.rn.f32", f[7], f[10], f[11], f[7])
                inst("add.f32", f[8], f[8], f[10])
                inst("add.u32", r[5], r[5], r[3])
                inst("bra", accLoop)
                place(accDone)
                inst("mov.u64", rd[12], ssum)
                inst("add.s64", rd[13], rd[12], rd[11])
                inst("st.shared.f32", mem(rd[13]), f[6])
                inst("mov.u64", rd[17], sdot)
                inst("add.s64", rd[18], rd[17], rd[11])
                inst("st.shared.f32", mem(rd[18]), f[7])
                inst("mov.u64", rd[19], slab)
                inst("add.s64", rd[15], rd[19], rd[11])
                inst("st.shared.f32", mem(rd[15]), f[8])
                inst("bar.sync", imm(0))
                comment("triple tree")
                inst("shr.u32", r[6], r[3], imm(1))
                val tredLoop = label("TRED_LOOP")
                val tredSkip = label("TRED_SKIP")
                val tredDone = label("TRED_DONE")
                place(tredLoop)
                inst("setp.eq.u32", p2, r[6], imm(0))
                inst("bra", tredDone, guard = p2)
                inst("setp.ge.u32", p3, r[2], r[6])
                inst("bra", tredSkip, guard = p3)
                inst("add.u32", r[7], r[2], r[6])
                inst("mul.wide.u32", rd[14], r[7], imm(4))
                inst("add.s64", rd[16], rd[12], rd[14])
                inst("ld.shared.f32", f[9], mem(rd[16]))
                inst("ld.shared.f32", f[10], mem(rd[13]))
                inst("add.f32", f[11], f[9], f[10])
                inst("st.shared.f32", mem(rd[13]), f[11])
                inst("add.s64", rd[16], rd[17], rd[14])
                inst("ld.shared.f32", f[9], mem(rd[16]))
                inst("ld.shared.f32", f[10], mem(rd[18]))
                inst("add.f32", f[11], f[9], f[10])
                inst("st.shared.f32", mem(rd[18]), f[11])
                inst("add.s64", rd[16], rd[19], rd[14])
                inst("ld.shared.f32", f[9], mem(rd[16]))
                inst("ld.shared.f32", f[10], mem(rd[15]))
                inst("add.f32", f[11], f[9], f[10])
                inst("st.shared.f32", mem(rd[15]), f[11])
                place(tredSkip)
                inst("bar.sync", imm(0))
                inst("shr.u32", r[6], r[6], imm(1))
                inst("bra", tredLoop)
                place(tredDone)
                blank()
                comment("thread 0: row_loss = dot - labSum * ln(sumExp)")
                val done = label("DONE")
                inst("setp.ne.u32", p4, r[2], imm(0))
                inst("bra", done, guard = p4)
                inst("ld.shared.f32", f[12], mem(rd[12]), comment = "sum exp")
                inst("ld.shared.f32", f[13], mem(rd[17]), comment = "dot")
                inst("ld.shared.f32", f[14], mem(rd[19]), comment = "lab sum")
                inst("lg2.approx.f32", f[15], f[12])
                inst("mul.f32", f[16], f[15], imm("0f3F317218"), comment = "* ln(2)")
                inst("mul.f32", f[17], f[14], f[16])
                inst("sub.f32", f[18], f[13], f[17])
                inst("mul.wide.u32", rd[9], r[1], imm(4))
                inst("add.s64", rd[10], rd[5], rd[9])
                inst("st.global.f32", mem(rd[10]), f[18])
                place(done)
                inst("ret")
            }

            kernel("kptx_cross_entropy_sum") {
                val rowLossPtr = param(".u64", "row_loss_ptr")
                val lossPtr = param(".u64", "loss_ptr")
                val nRowsP = param(".u32", "n_rows")

                val p1 = pred(); val p2 = pred(); val p3 = pred(); val p4 = pred()
                val r = List(6) { r32() }
                val f = List(6) { f32() }
                val rd = List(10) { r64() }
                val sacc = shared("sacc", sizeBytes = 4 * block)

                inst("ld.param.u64", rd[0], mem(rowLossPtr))
                inst("ld.param.u64", rd[1], mem(lossPtr))
                inst("ld.param.u32", r[0], mem(nRowsP))
                inst("cvta.to.global.u64", rd[2], rd[0])
                inst("cvta.to.global.u64", rd[3], rd[1])
                inst("mov.u32", r[1], tidX)
                inst("mov.u32", r[2], ntidX)
                blank()
                inst("mov.f32", f[0], imm("0f00000000"))
                inst("mov.u32", r[3], r[1])
                val loop = label("LOOP")
                val loopDone = label("LOOP_DONE")
                place(loop)
                inst("setp.ge.u32", p1, r[3], r[0])
                inst("bra", loopDone, guard = p1)
                inst("mul.wide.u32", rd[4], r[3], imm(4))
                inst("add.s64", rd[5], rd[2], rd[4])
                inst("ld.global.f32", f[1], mem(rd[5]))
                inst("add.f32", f[0], f[0], f[1])
                inst("add.u32", r[3], r[3], r[2])
                inst("bra", loop)
                place(loopDone)
                inst("mul.wide.u32", rd[6], r[1], imm(4))
                inst("mov.u64", rd[7], sacc)
                inst("add.s64", rd[8], rd[7], rd[6])
                inst("st.shared.f32", mem(rd[8]), f[0])
                inst("bar.sync", imm(0))
                inst("shr.u32", r[4], r[2], imm(1))
                val red = label("RED_LOOP")
                val redSkip = label("RED_SKIP")
                val redDone = label("RED_DONE")
                place(red)
                inst("setp.eq.u32", p2, r[4], imm(0))
                inst("bra", redDone, guard = p2)
                inst("setp.ge.u32", p3, r[1], r[4])
                inst("bra", redSkip, guard = p3)
                inst("add.u32", r[5], r[1], r[4])
                inst("mul.wide.u32", rd[9], r[5], imm(4))
                inst("add.s64", rd[4], rd[7], rd[9])
                inst("ld.shared.f32", f[2], mem(rd[4]))
                inst("ld.shared.f32", f[3], mem(rd[8]))
                inst("add.f32", f[4], f[2], f[3])
                inst("st.shared.f32", mem(rd[8]), f[4])
                place(redSkip)
                inst("bar.sync", imm(0))
                inst("shr.u32", r[4], r[4], imm(1))
                inst("bra", red)
                place(redDone)
                val done = label("DONE")
                inst("setp.ne.u32", p4, r[1], imm(0))
                inst("bra", done, guard = p4)
                inst("ld.shared.f32", f[5], mem(rd[7]))
                inst("st.global.f32", mem(rd[3]), f[5])
                place(done)
                inst("ret")
            }
        }
    }

    /**
     * §0.4.358 — attention forward (`O = softmax(Q·Kᵀ)·V`, the
     * FlashAttention COARSENED's math: operands `(Q[T,D], Kᵀ[D,T],
     * V[T,D])`, no scale factor, max-subtracting row softmax — exactly
     * the emitter's decomposition) as a **three-stage launch chain**
     * behind one custom_call. The score matrix `S[T,T]` lives in an
     * XLA-owned scratch result (the §0.4.350/351 mechanism):
     *
     *   1. `kptx_attn_scores(q, kt, S, n_t, n_d)` — CTA per score row,
     *      thread-strided columns, D-loop dot per element.
     *   2. `kptx_attn_softmax(S, n_t)` — CTA per row: strided max →
     *      tree, strided Σ exp(s−max) via `ex2(x·log2e)` → tree,
     *      strided normalize-in-place.
     *   3. `kptx_attn_out(S, v, o, n_t, n_d)` — CTA per output row,
     *      thread-strided dims, T-loop dot per element.
     *
     * Correctness-tier f32 loops by design — the claiming milestone;
     * the warp-specialized mma performance pass (TLX-informed, from the
     * §0.4.357-ingested bf16 GEMM tile) is the follow-up.
     */
    private val attnCache = HashMap<Int, PtxModule>()

    fun attentionModule(block: Int): PtxModule = attnCache.getOrPut(block) {
        // log2(e) = 0x3FB8AA3B (f32, bit-exact).
        ptxModule {
            kernel("kptx_attn_scores") {
                val qPtr = param(".u64", "q_ptr")
                val ktPtr = param(".u64", "kt_ptr")
                val sPtr = param(".u64", "s_ptr")
                val nTP = param(".u32", "n_t")
                val nDP = param(".u32", "n_d")

                val p1 = pred(); val p2 = pred()
                val r = List(7) { r32() }
                val f = List(3) { f32() }
                val rd = List(14) { r64() }

                inst("ld.param.u64", rd[0], mem(qPtr))
                inst("ld.param.u64", rd[1], mem(ktPtr))
                inst("ld.param.u64", rd[2], mem(sPtr))
                inst("ld.param.u32", r[0], mem(nTP))
                inst("ld.param.u32", r[1], mem(nDP))
                inst("cvta.to.global.u64", rd[3], rd[0])
                inst("cvta.to.global.u64", rd[4], rd[1])
                inst("cvta.to.global.u64", rd[5], rd[2])
                blank()
                inst("mov.u32", r[2], ctaidX)
                inst("mov.u32", r[3], tidX)
                inst("mov.u32", r[4], ntidX)
                comment("row bases: q row i*n_d, s row i*n_t; kt row stride in bytes")
                inst("mul.lo.u32", r[5], r[2], r[1])
                inst("mul.wide.u32", rd[6], r[5], imm(4))
                inst("add.s64", rd[7], rd[3], rd[6], comment = "q row")
                inst("mul.lo.u32", r[5], r[2], r[0])
                inst("mul.wide.u32", rd[6], r[5], imm(4))
                inst("add.s64", rd[8], rd[5], rd[6], comment = "s row")
                inst("mul.wide.u32", rd[9], r[0], imm(4), comment = "kt row stride bytes")
                blank()
                comment("for j strided: S[i,j] = sum_d Q[i,d] * Kt[d,j]")
                inst("mov.u32", r[5], r[3])
                val colLoop = label("COL_LOOP")
                val colDone = label("COL_DONE")
                place(colLoop)
                inst("setp.ge.u32", p1, r[5], r[0])
                inst("bra", colDone, guard = p1)
                inst("mul.wide.u32", rd[10], r[5], imm(4))
                inst("add.s64", rd[11], rd[4], rd[10], comment = "kt walking ptr, starts at [0,j]")
                inst("mov.u64", rd[12], rd[7], comment = "q walking ptr")
                inst("mov.f32", f[0], imm("0f00000000"))
                inst("mov.u32", r[6], imm(0))
                val dLoop = label("D_LOOP")
                val dDone = label("D_DONE")
                place(dLoop)
                inst("setp.ge.u32", p2, r[6], r[1])
                inst("bra", dDone, guard = p2)
                inst("ld.global.f32", f[1], mem(rd[12]))
                inst("ld.global.f32", f[2], mem(rd[11]))
                inst("fma.rn.f32", f[0], f[1], f[2], f[0])
                inst("add.s64", rd[12], rd[12], imm(4))
                inst("add.s64", rd[11], rd[11], rd[9])
                inst("add.u32", r[6], r[6], imm(1))
                inst("bra", dLoop)
                place(dDone)
                inst("add.s64", rd[13], rd[8], rd[10])
                inst("st.global.f32", mem(rd[13]), f[0])
                inst("add.u32", r[5], r[5], r[4])
                inst("bra", colLoop)
                place(colDone)
                inst("ret")
            }

            kernel("kptx_attn_softmax") {
                val sPtr = param(".u64", "s_ptr")
                val nTP = param(".u32", "n_t")

                val p1 = pred(); val p2 = pred(); val p3 = pred()
                val r = List(7) { r32() }
                val f = List(12) { f32() }
                val rd = List(11) { r64() }
                val smax = shared("smax", sizeBytes = 4 * block)

                inst("ld.param.u64", rd[0], mem(sPtr))
                inst("ld.param.u32", r[0], mem(nTP))
                inst("cvta.to.global.u64", rd[1], rd[0])
                blank()
                inst("mov.u32", r[1], ctaidX)
                inst("mov.u32", r[2], tidX)
                inst("mov.u32", r[3], ntidX)
                inst("mul.lo.u32", r[4], r[1], r[0])
                inst("mul.wide.u32", rd[2], r[4], imm(4))
                inst("add.s64", rd[3], rd[1], rd[2], comment = "s row")
                blank()
                comment("pass 1: strided row max + tree")
                inst("mov.f32", f[0], imm("0fFF800000"), comment = "-inf")
                inst("mov.u32", r[4], r[2])
                val maxLoop = label("MAX_LOOP")
                val maxDone = label("MAX_DONE")
                place(maxLoop)
                inst("setp.ge.u32", p1, r[4], r[0])
                inst("bra", maxDone, guard = p1)
                inst("mul.wide.u32", rd[4], r[4], imm(4))
                inst("add.s64", rd[5], rd[3], rd[4])
                inst("ld.global.f32", f[1], mem(rd[5]))
                inst("max.f32", f[0], f[0], f[1])
                inst("add.u32", r[4], r[4], r[3])
                inst("bra", maxLoop)
                place(maxDone)
                inst("mul.wide.u32", rd[6], r[2], imm(4))
                inst("mov.u64", rd[7], smax)
                inst("add.s64", rd[8], rd[7], rd[6])
                inst("st.shared.f32", mem(rd[8]), f[0])
                inst("bar.sync", imm(0))
                inst("shr.u32", r[5], r[3], imm(1))
                val mred = label("MRED_LOOP")
                val mredSkip = label("MRED_SKIP")
                val mredDone = label("MRED_DONE")
                place(mred)
                inst("setp.eq.u32", p2, r[5], imm(0))
                inst("bra", mredDone, guard = p2)
                inst("setp.ge.u32", p3, r[2], r[5])
                inst("bra", mredSkip, guard = p3)
                inst("add.u32", r[6], r[2], r[5])
                inst("mul.wide.u32", rd[9], r[6], imm(4))
                inst("add.s64", rd[10], rd[7], rd[9])
                inst("ld.shared.f32", f[2], mem(rd[10]))
                inst("ld.shared.f32", f[3], mem(rd[8]))
                inst("max.f32", f[4], f[2], f[3])
                inst("st.shared.f32", mem(rd[8]), f[4])
                place(mredSkip)
                inst("bar.sync", imm(0))
                inst("shr.u32", r[5], r[5], imm(1))
                inst("bra", mred)
                place(mredDone)
                inst("ld.shared.f32", f[5], mem(rd[7]), comment = "row max")
                inst("bar.sync", imm(0))
                blank()
                comment("pass 2: strided sum exp(s-max) + tree")
                inst("mov.f32", f[6], imm("0f00000000"))
                inst("mov.u32", r[4], r[2])
                val sumLoop = label("SUM_LOOP")
                val sumDone = label("SUM_DONE")
                place(sumLoop)
                inst("setp.ge.u32", p1, r[4], r[0])
                inst("bra", sumDone, guard = p1)
                inst("mul.wide.u32", rd[4], r[4], imm(4))
                inst("add.s64", rd[5], rd[3], rd[4])
                inst("ld.global.f32", f[1], mem(rd[5]))
                inst("sub.f32", f[7], f[1], f[5])
                inst("mul.f32", f[8], f[7], imm("0f3FB8AA3B"))
                inst("ex2.approx.f32", f[9], f[8])
                inst("add.f32", f[6], f[6], f[9])
                inst("add.u32", r[4], r[4], r[3])
                inst("bra", sumLoop)
                place(sumDone)
                inst("st.shared.f32", mem(rd[8]), f[6])
                inst("bar.sync", imm(0))
                inst("shr.u32", r[5], r[3], imm(1))
                val sred = label("SRED_LOOP")
                val sredSkip = label("SRED_SKIP")
                val sredDone = label("SRED_DONE")
                place(sred)
                inst("setp.eq.u32", p2, r[5], imm(0))
                inst("bra", sredDone, guard = p2)
                inst("setp.ge.u32", p3, r[2], r[5])
                inst("bra", sredSkip, guard = p3)
                inst("add.u32", r[6], r[2], r[5])
                inst("mul.wide.u32", rd[9], r[6], imm(4))
                inst("add.s64", rd[10], rd[7], rd[9])
                inst("ld.shared.f32", f[2], mem(rd[10]))
                inst("ld.shared.f32", f[3], mem(rd[8]))
                inst("add.f32", f[4], f[2], f[3])
                inst("st.shared.f32", mem(rd[8]), f[4])
                place(sredSkip)
                inst("bar.sync", imm(0))
                inst("shr.u32", r[5], r[5], imm(1))
                inst("bra", sred)
                place(sredDone)
                inst("ld.shared.f32", f[10], mem(rd[7]), comment = "row sum")
                blank()
                comment("pass 3: strided normalize in place")
                inst("mov.u32", r[4], r[2])
                val nrmLoop = label("NRM_LOOP")
                val nrmDone = label("NRM_DONE")
                place(nrmLoop)
                inst("setp.ge.u32", p1, r[4], r[0])
                inst("bra", nrmDone, guard = p1)
                inst("mul.wide.u32", rd[4], r[4], imm(4))
                inst("add.s64", rd[5], rd[3], rd[4])
                inst("ld.global.f32", f[1], mem(rd[5]))
                inst("sub.f32", f[7], f[1], f[5])
                inst("mul.f32", f[8], f[7], imm("0f3FB8AA3B"))
                inst("ex2.approx.f32", f[9], f[8])
                inst("div.rn.f32", f[11], f[9], f[10])
                inst("st.global.f32", mem(rd[5]), f[11])
                inst("add.u32", r[4], r[4], r[3])
                inst("bra", nrmLoop)
                place(nrmDone)
                inst("ret")
            }

            kernel("kptx_attn_out") {
                val sPtr = param(".u64", "s_ptr")
                val vPtr = param(".u64", "v_ptr")
                val oPtr = param(".u64", "o_ptr")
                val nTP = param(".u32", "n_t")
                val nDP = param(".u32", "n_d")

                val p1 = pred(); val p2 = pred()
                val r = List(7) { r32() }
                val f = List(3) { f32() }
                val rd = List(14) { r64() }

                inst("ld.param.u64", rd[0], mem(sPtr))
                inst("ld.param.u64", rd[1], mem(vPtr))
                inst("ld.param.u64", rd[2], mem(oPtr))
                inst("ld.param.u32", r[0], mem(nTP))
                inst("ld.param.u32", r[1], mem(nDP))
                inst("cvta.to.global.u64", rd[3], rd[0])
                inst("cvta.to.global.u64", rd[4], rd[1])
                inst("cvta.to.global.u64", rd[5], rd[2])
                blank()
                inst("mov.u32", r[2], ctaidX)
                inst("mov.u32", r[3], tidX)
                inst("mov.u32", r[4], ntidX)
                comment("row bases: s row i*n_t, o row i*n_d; v row stride bytes = n_d*4")
                inst("mul.lo.u32", r[5], r[2], r[0])
                inst("mul.wide.u32", rd[6], r[5], imm(4))
                inst("add.s64", rd[7], rd[3], rd[6], comment = "s row")
                inst("mul.lo.u32", r[5], r[2], r[1])
                inst("mul.wide.u32", rd[6], r[5], imm(4))
                inst("add.s64", rd[8], rd[5], rd[6], comment = "o row")
                inst("mul.wide.u32", rd[9], r[1], imm(4), comment = "v row stride bytes")
                blank()
                comment("for d strided: O[i,d] = sum_j P[i,j] * V[j,d]")
                inst("mov.u32", r[5], r[3])
                val dimLoop = label("DIM_LOOP")
                val dimDone = label("DIM_DONE")
                place(dimLoop)
                inst("setp.ge.u32", p1, r[5], r[1])
                inst("bra", dimDone, guard = p1)
                inst("mul.wide.u32", rd[10], r[5], imm(4))
                inst("add.s64", rd[11], rd[4], rd[10], comment = "v walking ptr, starts at [0,d]")
                inst("mov.u64", rd[12], rd[7], comment = "p walking ptr")
                inst("mov.f32", f[0], imm("0f00000000"))
                inst("mov.u32", r[6], imm(0))
                val jLoop = label("J_LOOP")
                val jDone = label("J_DONE")
                place(jLoop)
                inst("setp.ge.u32", p2, r[6], r[0])
                inst("bra", jDone, guard = p2)
                inst("ld.global.f32", f[1], mem(rd[12]))
                inst("ld.global.f32", f[2], mem(rd[11]))
                inst("fma.rn.f32", f[0], f[1], f[2], f[0])
                inst("add.s64", rd[12], rd[12], imm(4))
                inst("add.s64", rd[11], rd[11], rd[9])
                inst("add.u32", r[6], r[6], imm(1))
                inst("bra", jLoop)
                place(jDone)
                inst("add.s64", rd[13], rd[8], rd[10])
                inst("st.global.f32", mem(rd[13]), f[0])
                inst("add.u32", r[5], r[5], r[4])
                inst("bra", dimLoop)
                place(dimDone)
                inst("ret")
            }
        }
    }

    /**
     * RMS-norm backward, dw half: `dw_j = Σ_i dy_ij·x_ij·inv_rms_i`,
     * consuming the `inv_rms` vector [rmsNormBwdDx] produced (XLA
     * sequences the two custom_calls via the data dependence). One
     * thread per column. Launch signature:
     * `(x_ptr, dy_ptr, invr_ptr, dw_ptr, n_rows, n_cols)`.
     */
    val rmsNormBwdDw: PtxKernelTemplate = PtxKernelTemplate("kptx_rms_norm_bwd_dw") { _ ->
        val xPtr = param(".u64", "x_ptr")
        val dyPtr = param(".u64", "dy_ptr")
        val invrPtr = param(".u64", "invr_ptr")
        val dwPtr = param(".u64", "dw_ptr")
        val nRowsP = param(".u32", "n_rows")
        val nColsP = param(".u32", "n_cols")

        val p1 = pred(); val p2 = pred()
        val r = List(8) { r32() }
        val f = List(5) { f32() }
        val rd = List(15) { r64() }

        inst("ld.param.u64", rd[0], mem(xPtr))
        inst("ld.param.u64", rd[1], mem(dyPtr))
        inst("ld.param.u64", rd[2], mem(invrPtr))
        inst("ld.param.u64", rd[3], mem(dwPtr))
        inst("ld.param.u32", r[0], mem(nRowsP))
        inst("ld.param.u32", r[1], mem(nColsP))
        inst("cvta.to.global.u64", rd[4], rd[0])
        inst("cvta.to.global.u64", rd[5], rd[1])
        inst("cvta.to.global.u64", rd[6], rd[2])
        inst("cvta.to.global.u64", rd[7], rd[3])
        blank()
        comment("column j = ctaid * ntid + tid; guard j < n_cols")
        inst("mov.u32", r[2], ctaidX)
        inst("mov.u32", r[3], ntidX)
        inst("mov.u32", r[4], tidX)
        inst("mad.lo.u32", r[5], r[2], r[3], r[4])
        val done = label("DONE")
        inst("setp.ge.u32", p1, r[5], r[1])
        inst("bra", done, guard = p1)
        blank()
        comment("dw_j = sum_i dy[i,j] * x[i,j] * inv_rms[i]")
        inst("mov.f32", f[0], imm("0f00000000"))
        inst("mov.u32", r[6], imm(0))
        val loopRows = label("LOOP_ROWS")
        val rowsDone = label("ROWS_DONE")
        place(loopRows)
        inst("setp.ge.u32", p2, r[6], r[0])
        inst("bra", rowsDone, guard = p2)
        inst("mad.lo.u32", r[7], r[6], r[1], r[5])
        inst("mul.wide.u32", rd[8], r[7], imm(4))
        inst("add.s64", rd[9], rd[4], rd[8])
        inst("ld.global.f32", f[1], mem(rd[9]))
        inst("add.s64", rd[10], rd[5], rd[8])
        inst("ld.global.f32", f[2], mem(rd[10]))
        inst("mul.wide.u32", rd[11], r[6], imm(4))
        inst("add.s64", rd[12], rd[6], rd[11])
        inst("ld.global.f32", f[3], mem(rd[12]))
        inst("mul.f32", f[4], f[2], f[1])
        inst("fma.rn.f32", f[0], f[4], f[3], f[0])
        inst("add.u32", r[6], r[6], imm(1))
        inst("bra", loopRows)
        place(rowsDone)
        inst("mul.wide.u32", rd[13], r[5], imm(4))
        inst("add.s64", rd[14], rd[7], rd[13])
        inst("st.global.f32", mem(rd[14]), f[0])
        place(done)
        inst("ret")
    }
}
